-- Options for Pokemon Stadium 2 Overworld Models - Gold/Silver (Gen 2).
-- Includes the embedded Wilds of Kanto roaming-spawn controls so this ZIP is standalone.
return {
  {
    key = "voxel3d",
    type = "toggle",
    label = "3D VOXEL WORLD",
    default = true,
    description = "Enables the Gold Gen-2 voxel renderer through render.compose. v0.1.72 primes the current Gold map into a real voxel mesh immediately and reports mesh failures instead of silently staying flat. v0.1.74 keeps that voxel world active and redraws Gold START/textbox overlays visibly above it. Stadium 2 ROM selection is not required for the terrain itself.",
  },
  {
    key = "cameraMode",
    type = "choice",
    label = "3D CAMERA MODE",
    default = "diorama",
    choices = {
      { "DIORAMA", "diorama" },
      { "THIRD PERSON", "third" },
      { "FIRST PERSON", "first" },
    },
    description = "Select the Gold voxel-world camera. DIORAMA keeps the existing view, THIRD PERSON follows behind the player, and FIRST PERSON places the camera at the player's head. F6 cycles modes. In THIRD/FIRST PERSON, Gold keeps its native grid movement but the controls are camera-relative: UP/W is forward, DOWN/S is back, and LEFT/RIGHT strafe relative to the view.",
  },
  {
    key = "partyFollower",
    type = "toggle",
    label = "LEAD PARTY FOLLOWER",
    default = true,
    description = "Makes party slot #1 follow directly behind the player using Gold's native Gen-2 follower trail, like Pokemon Yellow. The follower uses its Stadium 2 3D model in voxel mode and updates automatically when party order changes. Hidden while biking or surfing.",
  },
  {
    key = "battle3dWorld",
    type = "toggle",
    label = "LIVE OVERWORLD BATTLES",
    default = true,
    description = "ON (default): ordinary wild battles stay in the exact voxel overworld view where the encounter began, using the same map, camera, weather and terrain while Gold keeps its native battle UI and logic. OFF: use Gold's classic battle scene. This can be changed without uninstalling the mod.",
  },
  {
    key = "weatherMode",
    type = "choice",
    label = "3D WEATHER",
    default = "auto",
    choices = {
      { "AUTO", "auto" },
      { "CLEAR", "clear" },
      { "RAIN", "rain" },
      { "FOG", "fog" },
      { "RAIN + FOG", "rain_fog" },
    },
    description = "Outdoor Gold voxel weather. AUTO slowly cycles conditions; the other choices force one. Interiors stay clear.",
  },
  {
    key = "weatherClouds",
    type = "toggle",
    label = "MOVING CLOUDS",
    default = true,
    description = "Moving pixel-cloud layers behind the 3D world. The existing day/night sky keeps the sun by day and moon by night.",
  },
  {
    key = "stadiumRomFile",
    type = "choice",
    label = "STADIUM 2 ROM FILE (GEN 2)",
    default = "choose",
    choices = {
      { "CHOOSE", "choose" },
    },
    description = "Choose your legally obtained Pokemon Stadium 2 ROM to build 3D models for National Dex 1-251.",
  },
  -- ------- Core gameplay
  {
    key = "enabled",
    label = "Show Wild Mons",
    type = "toggle",
    default = true,
    description = "Spawn visible wild Pokemon in eligible overworld encounter areas.",
  },
  {
    key = "sprite_style",
    label = "Sprite Style",
    type = "choice",
    default = "followers",
    choices = {
      { "Poke Followers / GSC", "followers" },
      { "HGSS / PokeMMO", "pokemmo" },
      { "Pokédex", "pokedex" },
    },
    description = "Overworld sprite style for wild Pokémon and followers. Poke Followers / GSC is the built-in default. Water Pokémon still use Swimming or Levitates sprites when available.",
  },
  {
    key = "sprite_fade",
    label = "Sprite Fade",
    type = "choice",
    default = "solid",
    choices = {
      { "Solid", "solid" },
      { "Faded", "faded" },
    },
    description = "Opacity of normal visible wild Pokémon. Solid is fully opaque. Faded uses the classic semi-transparent wild look. Does not affect followers, Town Pokémon, silhouettes, or UI.",
  },
  {
    key = "follow_control",
    label = "Control Mode",
    type = "choice",
    default = "trainer",
    choices = {
      { "Trainer", "trainer" },
      { "Pokémon", "pokemon" },
    },
    description = "Choose whether you control the trainer or the selected Pokémon.",
  },
  {
    key = "trainer_trail",
    label = "Trainer Trail",
    type = "toggle",
    default = false,
    description = "When controlling a Pokémon, the trainer follows behind.",
  },
  {
    key = "follower_count",
    label = "Followers",
    type = "choice",
    default = 1,
    choices = {
      { "0", 0 },
      { "1", 1 },
      { "2", 2 },
      { "3", 3 },
      { "4", 4 },
      { "5", 5 },
      { "6", 6 },
    },
    description = "Number of additional party Pokémon following the active leader.",
  },
  {
    key = "spawn_density",
    label = "Spawn Amount",
    type = "choice",
    default = "normal",
    choices = {
      { "Low", "low" },
      { "Normal", "normal" },
      { "High", "high" },
      { "Very High", "very_high" },
    },
    description = "Controls how many visible overworld Pokémon can appear. This also affects visible water Pokémon.",
  },
  {
    key = "random_encounters",
    label = "Classic Step Enc",
    type = "toggle",
    default = false,
    description = "OFF is the visible-only mode: normal grass/cave step encounters are blocked so every ordinary encounter comes from a Pokemon you can see and touch. Turn ON only if you also want classic invisible random steps.",
  },
  {
    key = "water_spawns",
    label = "Water Mons",
    type = "choice",
    default = "swimming_sprites",
    choices = {
      { "Swim Sprites", "swimming_sprites" },
      { "Hid Silhouette", "hidden_silhouettes" },
      { "Silhouettes", "silhouettes" },
      { "Classic Enc", "classic_encounters" },
      { "Disabled", "disabled" },
    },
    description = "How water Pokémon appear: swimming sprites (default), hidden dark circles, tinted silhouettes, classic random encounters only, or fully disabled.",
  },
  {
    key = "cave_spawns",
    label = "Cave Spawns",
    type = "choice",
    default = "reachable",
    choices = {
      { "Reachable Only", "reachable" },
      { "Mixed", "mixed" },
    },
    description = "Cave Pokémon spawn only on tiles the player can reach, or Mixed (~20% atmospheric scenery in inaccessible cave pockets).",
  },
  {
    key = "town_pokemon",
    label = "Town Pokémon",
    type = "toggle",
    default = true,
    description = "Adds peaceful Pokémon to safe towns and interiors. They behave like NPCs and cannot start battles.",
  },
  {
    key = "pokemon_grass_render_mode",
    label = "Grass View",
    type = "choice",
    default = "immersed",
    choices = {
      { "Above", "above" },
      { "Immersed", "immersed" },
    },
    description = "Draw wild Pokemon fully above tall grass, or partially hidden inside it like the player and trainers.",
  },
  {
    key = "wild_silhouettes",
    label = "Enc Silhouette",
    type = "toggle",
    default = false,
    description = "Black out overworld wild Pokémon in encounter zones (grass/cave/water) as silhouettes, keeping their shapes. Derived from the coloured art at load — no extra sprite files.",
  },
  {
    key = "enable_idle",
    label = "Idle Mons",
    type = "toggle",
    default = true,
    description = "Allow Idle Look behaviour (stand still, glance around).",
  },
  {
    key = "enable_wander",
    label = "Roam Mons",
    type = "toggle",
    default = true,
    description = "Allow wander behaviour within a connected encounter region.",
  },
  {
    key = "enable_aggressive",
    label = "Chase Mons",
    type = "toggle",
    default = true,
    description = "Allow aggressive Pokemon that spot, chase, and force a battle.",
  },
  {
    key = "enable_hidden",
    label = "Hidden Mons",
    type = "toggle",
    default = false,
    description = "Disabled for Gold/Silver visible-roaming mode; encounter Pokemon are shown on the map.",
  },

  -- ------- Developer (only Dev Overlay + Test Spawn)
  {
    key = "dev_overlay",
    label = "Dev Overlay",
    type = "toggle",
    default = false,
    description = "Shows each wild Pokémon's behaviour and facing direction above it.",
  },
}
