-- Options for Pokemon Stadium 2 Overworld Models - Gold/Silver (Gen 2).
-- Includes the embedded Wilds of Kanto roaming-spawn controls so this ZIP is standalone.
local schema = {
  {
    key = "performancePreset",
    type = "choice",
    label = "PERFORMANCE PRESET",
    default = "auto",
    choices = {
      { "AUTO / RECOMMENDED", "auto" },
      { "LOW", "low" },
      { "MEDIUM", "medium" },
      { "HIGH", "high" },
      { "ULTRA", "ultra" },
      { "CUSTOM", "custom" },
    },
    description = "PC-style master graphics preset. AUTO / RECOMMENDED is the new default and watches real voxel draw cost, stepping between LOW/MEDIUM/HIGH with long hysteresis so it reacts to slow hardware without constantly changing quality. LOW prioritizes frame rate, MEDIUM is the stable balanced tier, HIGH raises world/shadow quality while keeping the fast sky-water reflection path, ULTRA restores full-resolution maximum-distance rendering and FULL SSR, and CUSTOM uses the individual graphics rows below. Changing ANY individual graphics row automatically switches this master row to CUSTOM so the change takes effect immediately. Every preset keeps voxel terrain, Kanto, NPCs, Pokemon, ocean, battles, weather and 3D models available; lower presets stream/cull distant work instead of deleting features.",
  },
  {
    key = "frameRateLimit",
    type = "choice",
    label = "FRAME RATE LIMIT",
    default = "60",
    choices = {
      { "30 FPS", "30" }, { "45 FPS", "45" }, { "60 FPS", "60" },
      { "90 FPS", "90" }, { "120 FPS", "120" }, { "144 FPS", "144" },
      { "UNLIMITED", "unlimited" },
    },
    description = "Caps presentation frame rate without changing Gold's fixed 60 Hz gameplay clock, music tempo or movement speed. 60 FPS is the recommended default and prevents the voxel renderer from burning CPU/GPU just to feed 120/144/165 Hz displays. UNLIMITED restores the host's normal uncapped/vsync behavior.",
  },
  {
    key = "graphicsResolution",
    type = "choice",
    label = "3D RENDER RESOLUTION",
    default = "55",
    choices = {
      { "40%", "40" }, { "55%", "55" }, { "75%", "75" }, { "100%", "100" },
    },
    description = "Individual PC graphics control. Changing this row automatically selects CUSTOM. Sets internal voxel render resolution before the finished frame is scaled to the window; terrain, depth, weather and reflective water share this 3D target.",
  },
  {
    key = "graphicsShadows",
    type = "choice",
    label = "SHADOW QUALITY",
    default = "blob",
    choices = {
      { "OFF", "off" }, { "BLOB / FAST", "blob" }, { "LOW", "low" }, { "HIGH", "high" }, { "SOFT / WIDE", "soft" },
    },
    description = "Individual PC graphics control; changing it automatically selects CUSTOM. BLOB / FAST is the recommended low-cost mode: soft contact shadows under actors with NO second terrain render or shadow-map texture. LOW/HIGH/SOFT use progressively heavier real sun shadow maps. OFF draws no shadows. BLOB / FAST is substantially cheaper and avoids the noisy blocky shadow-map look on lower-end PCs/Android.",
  },
  {
    key = "graphicsReflections",
    type = "choice",
    label = "WATER REFLECTIONS",
    default = "sky",
    choices = {
      { "SKY / FAST", "sky" }, { "FULL SSR", "full" }, { "OFF", "off" },
    },
    description = "Individual PC graphics control; changing it automatically selects CUSTOM. SKY keeps animated reflective water, sky/sun/moon color and waves without the expensive screen-space world ray march. FULL SSR reflects visible terrain/characters. OFF uses the ordinary animated water surface.",
  },
  {
    key = "graphicsDrawDistance",
    type = "choice",
    label = "WORLD DRAW DISTANCE",
    default = "balanced",
    choices = {
      { "NEAR", "near" }, { "BALANCED", "balanced" }, { "FAR", "far" }, { "MAX", "max" },
    },
    description = "Individual PC graphics control; changing it automatically selects CUSTOM. Controls how far outside the camera the renderer keeps distant voxel sectors and actors drawable. Culling is presentation-only: maps/NPCs/Pokemon are not deleted and stream back immediately when the camera or player approaches them.",
  },
  {
    key = "graphicsKantoRadius",
    type = "choice",
    label = "KANTO SECTOR PREFETCH",
    default = "2",
    choices = { { "1 RING", "1" }, { "2 RINGS", "2" }, { "3 RINGS", "3" } },
    description = "Individual PC graphics control; changing it automatically selects CUSTOM. Number of connected Pokemon Yellow map rings prepared around the current Kanto map while walking there. Seam crossing always re-roots the streamer, so lower values reduce background work without removing connected Kanto areas.",
  },
  {
    key = "graphicsBuildRate",
    type = "choice",
    label = "MESH BUILD RATE",
    default = "balanced",
    choices = {
      { "SMOOTH", "smooth" }, { "BALANCED", "balanced" }, { "FAST LOAD", "fast" },
    },
    description = "Individual PC graphics control; changing it automatically selects CUSTOM. Controls the milliseconds per frame given to asynchronous voxel mesh/Yellow-atlas preparation. SMOOTH minimizes frame hitches; FAST LOAD makes new sectors appear sooner but spends more CPU each frame.",
  },
  {
    key = "voxel3d",
    type = "toggle",
    label = "3D VOXEL WORLD",
    default = true,
    description = "Master switch for the overworld renderer. ON uses this mod's Gold/Silver voxel world. OFF is now a first-class native 2D mode: Gold's real 2D map stays authoritative, OPEN WORLD cannot turn voxels back on, first/third-person camera input releases immediately, native 2D zoom is restored, Weather FX falls back to its 2D presentation, visible wild Pokemon keep their 2D sprites, and custom pause/settings UI can remain over the live 2D world. The 3D-only shoulder-aim capture minigame stands down in 2D and normal visible-wild battles/catching remain available. Yellow KANTO FREE ROAM is currently a mod-owned foreign-map presentation and therefore refuses entry while 2D is selected instead of silently forcing 3D; disabling 3D during a Kanto visit returns safely to the saved Johto anchor. Native TILT OFF uses the normal 35-degree voxel diorama only while 3D is ON. Stadium 2 ROM selection is not required for terrain.",
  },
  {
    key = "customUI",
    type = "toggle",
    label = "CUSTOM UI / MENUS",
    default = true,
    description = "ON uses this mod's custom translucent Stadium-style pause menu, Pokedex/Party/Pack/Pokegear/Trainer/Save/Options screens, custom Mod Manager presentation and custom live-battle HUD. OFF hands those screens back to Gold/Gen1Recomp's original menu renderers and native battle UI while leaving voxel terrain, OPEN WORLD, weather, models and other non-UI features enabled. The direct MOD SETTINGS pause shortcut is also hidden while OFF; use MODS > this mod > OPTIONS to turn it back ON.",
  },
  {
    key = "uiTextSize",
    type = "number",
    label = "UI TEXT SIZE %",
    default = 100,
    min = 75,
    max = 160,
    step = 5,
    description = "Scales the text used by this mod's modern Mod Settings app grid and category lists without making the slim setting rows taller. 100% matches the normal interface size; raise it for easier reading on phones/TVs or lower it to fit more text. LEFT/RIGHT changes by 5%, A opens the numeric picker, and changes apply immediately.",
  },
  {
    key = "controllerLayout",
    type = "choice",
    label = "CONTROLLER LAYOUT",
    default = "playstation",
    choices = {
      { "PLAYSTATION", "playstation" },
      { "XBOX", "xbox" },
      { "NINTENDO SWITCH", "switch" },
    },
    description = "Chooses the controller family used by this mod's battle UI and custom menu navigation. PLAYSTATION shows Square/Triangle/Cross/Circle with Cross confirm and Circle back. XBOX shows X/Y/A/B with A confirm and B back. NINTENDO SWITCH shows Y/X/B/A by physical face-button position and uses Nintendo-style A (east) confirm / B (south) back, including the Mod Manager and Gold custom menus.",
  },
  {
    key = "showFpsCounter",
    type = "toggle",
    label = "FPS COUNTER",
    default = false,
    description = "Shows a small live FPS readout in the top-left corner of the game window. This is presentation-only and has negligible overhead.",
  },
  {
    key = "shoulderSpeedControl",
    type = "toggle",
    label = "L1/R1 GAME SPEED",
    default = false,
    description = "OFF blocks Gen1Recomp's built-in shoulder-button game-speed cycling, so PlayStation L1/R1 and Xbox/Switch LB/RB cannot accidentally put Gold into fast-forward. ON restores the engine behavior. This does not disable trigger controls such as L2/R2 aiming or mount controls.",
  },
  {
    key = "stadium3dSprites",
    type = "toggle",
    label = "3D POKéMON MODELS",
    default = true,
    description = "Controls Pokemon models only. ON uses Stadium 2 3D models for roaming/wild Pokemon, the party follower, live-battle combatants and custom Pokedex/Party/battle previews. OFF keeps the voxel terrain, 3D scenery and OPEN WORLD renderer but returns Pokemon to their normal Gold 2D sprite/card presentation. The human player's 3D model is controlled separately below.",
  },
  {
    key = "customPlayerSprite",
    type = "toggle",
    label = "CUSTOM PLAYER SPRITE",
    default = false,
    description = "Use your imported animated trainer sheet as Gold's player sprite. The custom sprite follows normal turning, walking cadence, bike-speed steps, ledge jumps and the voxel billboard pose system. When ON, it takes visual priority over the Character Selector 3D player model. OFF restores the normal Gold/Character Selector player.",
  },
  {
    key = "customPlayerSpriteFile",
    type = "choice",
    label = "PLAYER SPRITE SHEET",
    default = "choose",
    choices = {
      { "CHOOSE", "choose" },
    },
    description = "Animated custom player image. A/Confirm or Right opens the PC/Android picker; Left removes it. Sheet format is ONE VERTICAL STRIP of 6 equal frames: Stand Down, Stand Up, Stand Left, Walk Down, Walk Up, Walk Left. Right is mirrored automatically. PNG with transparency is recommended; JPEG/BMP are also accepted.",
  },
  {
    key = "player3dModel",
    type = "toggle",
    label = "3D PLAYER MODEL",
    default = true,
    description = "Controls the human player model only. ON allows red_3d_player / 3D Character Selector to draw the currently selected 3D player skin inside the voxel world. OFF forces the player back to Gold's normal 2D trainer sprite/card while leaving Stadium Pokemon models, followers, battles, Pokedex previews, voxel terrain and OPEN WORLD untouched.",
  },
  {
    key = "openWorld",
    type = "toggle",
    label = "OPEN WORLD",
    default = false,
    description = "OFF (default) keeps the performance-friendly 3D streamer in both Johto and Yellow Kanto. ON expands voxel residency to the full cardinally connected outdoor graph of the region you are currently visiting: Johto uses its connected Gold graph, while KANTO FREE ROAM progressively prepares the complete Yellow outdoor graph around the current Kanto map. Persistent sector-cache hits are reused as those Kanto maps join. OPEN WORLD does NOT force 3D VOXEL WORLD on: if the voxel master switch is OFF, Gold/Silver stays in native 2D and this residency preference waits until voxels are enabled again. This can use much more RAM/VRAM/CPU/GPU while voxels are active; switch OFF to return to normal sector streaming and release far meshes.",
  },
  {
    key = "worldOcean",
    type = "toggle",
    label = "WORLD OCEAN",
    default = false,
    description = "Adds reflective ocean ONLY around the outside perimeter of rendered land instead of one giant plane underneath the maps. It now works during KANTO FREE ROAM too: with OPEN WORLD OFF the ocean follows the currently streamed Kanto sector, and with OPEN WORLD ON it expands progressively to the perimeter of the complete prepared Yellow outdoor graph. Native lakes/rivers keep their own water, and offscreen perimeter strips do not trigger the expensive reflection pass. OFF preserves the existing outer voxel apron/void behavior.",
  },
  {
    key = "gen1Region",
    type = "toggle",
    label = "GEN-1 KANTO REGION",
    default = false,
    description = "Pokemon Yellow Kanto as a story-free second region for Gold/Silver. v0.4.01 restores the Summer Beach House and native Surfing Pikachu minigame for a Gold-party Pikachu that knows SURF, with a Kanto-local high score and visit-local printer behavior; v0.4.00 restores reliable Pokemon Center healing plus the full foreign-Kanto void-tree belt; v0.3.95 restores Celadon rooftop drink-girl parity with persistent Kanto-local Yellow TM credits for ICE BEAM, ROCK SLIDE and TRI ATTACK, using Yellow compatibility instead of unrelated Gen-2 TM numbers; v0.3.91 restores Safari/Fuchsia HM progression: GOLD TEETH are Kanto-local, the Warden gives Gold STRENGTH, the Secret House gives Gold SURF, and Yellow field HMs use Yellow Kanto badge requirements; v0.3.90 restores the Cerulean bridge, Pokemon Tower 2F and late Route 22 Rival encounters through Gold battles and makes the Kanto Hall of Fame physically unlock Cerulean Cave/Mewtwo; v0.3.89 restores the complete Pokemon League run: Lorelei, Bruno, Agatha and Lance use Yellow rosters in Gold battles; their authored room gates open after victory; the active run is forward-only; Lance seals the entrance behind the player; the Yellow RIVAL3 Champion fight leads into Gold's native Hall of Fame record/animation and a safe Kanto rematch reset. v0.3.88 Silph/Saffron liberation, v0.3.87 Bill/S.S. Anne progression, v0.3.86 static encounters, v0.3.85 dungeon puzzles, v0.3.82 mesh cleanup and v0.3.78 Johto-matched colors remain intact. Yellow story/cutscene ASM remains isolated from Gold save state.",
  },
  {
    key = "voxelDiskCache",
    type = "toggle",
    label = "PERSISTENT SECTOR CACHE",
    default = true,
    description = "v0.3.32 rebuilt persistent voxel caching safely around Gen1Recomp's engine-owned save/portable filesystem. ON stores validated raw BODY/FULL terrain meshes on disk and reloads them in cooperative upload chunks, so revisiting a route/sector skips Structures + geometry generation. Yellow Kanto also cooks its outdoor BODY sectors in the background when real render work is idle; desktop uses a much larger warm-up CPU slice than mobile. Cache entries are revision/map/tile/UV/seam-mask signed and metadata commits last, so stale or interrupted files are misses instead of corrupted worlds. Turn OFF to use only the normal in-memory mesh cache.",
  },
  {
    key = "cameraControl",
    type = "choice",
    label = "CAMERA CONTROL",
    default = "auto",
    choices = {
      { "AUTO", "auto" },
      { "THIS MOD", "stadium" },
      { "CHARACTER SELECTOR", "selector" },
    },
    description = "AUTO gives red_3d_player / 3D Character Selector control of ZOOM, 1ST and 3RD camera modes when that mod is installed; otherwise this mod controls the camera. THIS MOD always uses the 3D CAMERA MODE option below. CHARACTER SELECTOR explicitly follows the engine voxel camera level and leaves the selector's Gen-2 movement controls untouched.",
  },
  {
    key = "cameraMode",
    type = "choice",
    label = "3D CAMERA MODE",
    default = "diorama",
    choices = {
      { "DIORAMA", "diorama" },
      { "THIRD PERSON", "third" },
      { "FIRST PERSON", "first" },
    },
    description = "Camera used by the voxel world. On Android, a 3-position in-game touch slider switches DIORAMA / THIRD PERSON / FIRST PERSON. On desktop, F6 cycles the same three modes. In THIRD/FIRST PERSON, mouse-look and a controller right stick both rotate the camera. When Character Selector owns the camera, the Android slider/F6 changes its public ZOOM / 3RD / 1ST voxel rung instead of overriding the selector.",
  },
  {
    key = "worldZoomRange",
    type = "choice",
    label = "OPEN WORLD ZOOM LIMIT",
    default = "world",
    choices = {
      { "STANDARD 2.2X", "standard" },
      { "FAR 4X", "far" },
      { "WORLD 8X", "world" },
      { "EXTREME 12X", "extreme" },
      { "TWIN 16X", "twin" },
      { "ATLAS 24X", "atlas" },
    },
    description = "Maximum DIORAMA camera distance available through wheel/trackpad/pinch zoom while the voxel world is active. STANDARD keeps 2.2x; FAR reaches 4x; WORLD (default) reaches 8x; EXTREME reaches 12x; TWIN 16x and ATLAS 24x are twin-region survey ranges. While 3D is ON, OPEN WORLD or GEN-1 KANTO REGION can also unlock the extended engine survey rung for Character Selector/native ZOOM compatibility. While 3D VOXEL WORLD is OFF, this setting is inert and Gold's native 2D zoom range is left untouched.",
  },
  {
    key = "cameraSlider",
    type = "toggle",
    label = "ANDROID CAMERA SLIDER",
    default = true,
    description = "Shows the DIORAMA / 3RD / 1ST touch slider at the top of the screen on Android. Turn this OFF to completely hide the slider and release its touch area for camera look/pinch gestures.",
  },
  {
    key = "screenFlip",
    type = "toggle",
    label = "FLIP SCREEN 180 DEGREES",
    default = false,
    description = "Android emergency reverse-landscape helper. Rotates the ENTIRE finished Gold game frame 180 degrees after all rendering, including voxel world, menus, battle UI, overlays and on-screen touch controls. Touch coordinates are remapped by the same 180-degree transform so buttons still line up. Use this as a compatibility workaround on Android devices that insist on the wrong landscape side.",
  },
  {
    key = "iosOrientationFix",
    type = "toggle",
    label = "IPHONE ORIENTATION FIX",
    default = true,
    description = "iPhone/iPad orientation compatibility. ON explicitly asks SDL/UIKit to allow normal portrait plus BOTH landscape directions, then leaves framebuffer/touch rotation entirely native. The mod never auto-rotates a landscapeFlipped frame anymore, preventing the old double-180 upside-down bug. Current Gen1Recomp's iOS-aware Orientation path is used as a fallback if direct SDL hinting is unavailable. Leave ON for normal use.",
  },
  {
    key = "iosForceFlip",
    type = "toggle",
    label = "IPHONE FORCE 180",
    default = false,
    description = "Emergency iOS fallback only. Forces one final 180-degree frame rotation and remaps touches too. Leave OFF for normal iPhone/iPad builds; automatic iOS frame flipping has been removed, so this should only be needed for a genuinely broken custom/sideload runtime.",
  },
  -- ------- Fly Your Pokemon / mounted traversal
  { key = "mountFlightMode", type = "toggle", label = "FLY", default = false,
    description = "Actual free-flight switch. Turn ON to mount the selected eligible party Pokemon and fly freely around the overworld. While flying, PlayStation Circle / Xbox B / Switch B queues the safe deferred LAND action. Cross/A, Square/X, Triangle/Y, START and SELECT are quarantined from Gold until Flight ends. H also toggles Flight on keyboard. Turn this setting OFF to land/dismount too. A fresh boot or save load always resets it to OFF so a crash can never relaunch you already flying." },
  { key = "mountFlightPokemon", type = "choice", label = "FLYING POKéMON", default = "auto",
    choices = {
      {"AUTO / ELIGIBLE PARTY MON","auto"},
      {"CHARIZARD","CHARIZARD"}, {"PIDGEOT","PIDGEOT"}, {"FEAROW","FEAROW"},
      {"GOLBAT","GOLBAT"}, {"AERODACTYL","AERODACTYL"}, {"ARTICUNO","ARTICUNO"},
      {"ZAPDOS","ZAPDOS"}, {"MOLTRES","MOLTRES"}, {"DRAGONAIR","DRAGONAIR"},
      {"DRAGONITE","DRAGONITE"}, {"NOCTOWL","NOCTOWL"}, {"CROBAT","CROBAT"},
      {"XATU","XATU"}, {"SKARMORY","SKARMORY"}, {"LUGIA","LUGIA"}, {"HO-OH","HO_OH"},
    },
    description = "Choose which eligible party Pokemon you ride when FLY is ON. AUTO uses the currently selected/first eligible flying party Pokemon. If the chosen species is not eligible, Flight stays off and tells you why." },
  { key = "mountSettingsView", type = "choice", label = "MOUNT SETTINGS VIEW", default = "simple",
    choices = { {"SIMPLE","simple"},{"ADVANCED","advanced"} },
    description = "SIMPLE shows the main ride/fly controls. ADVANCED exposes progression, camera, encounter, feedback and integration controls." },
  { key = "mountShowRider", type = "toggle", label = "SHOW RIDER", default = true, description = "Draw the trainer riding above the active Pokemon mount. OFF shows only the Pokemon." },
  { key = "mountFlightSpeed", type = "number", label = "FLIGHT SPEED %", default = 100, min = 50, max = 200, step = 10, description = "Air travel speed from 50% to 200%." },
  { key = "mountGroundSpeed", type = "number", label = "GROUND SPEED %", default = 120, min = 50, max = 200, step = 10, description = "Ground Ride movement speed from 50% to 200%." },
  { key = "mountManualAltitude", type = "toggle", label = "MANUAL ALTITUDE", default = true, description = "Page Up/Page Down or controller R2/L2 raises and lowers the flying mount." },
  { key = "mountVisibleSurf", type = "toggle", label = "VISIBLE SURF MOUNTS", default = true, description = "Shows an eligible party Pokemon as the mount while Gold's normal Surf state is active." },
  { key = "mountRealisticSizes", type = "toggle", label = "REALISTIC MOUNT SIZES", default = true, description = "Uses species-aware mount presentation scale instead of making every Pokemon the same visual size." },
  { key = "mountHints", type = "toggle", label = "MOUNT HINTS", default = true, description = "Shows concise controls/status hints while mounted." },
  { key = "mountCries", type = "toggle", label = "MOUNT CRIES", default = true, description = "Play the selected Pokemon's cry when mounting where the engine cry service is available." },
  { key = "mountMenu", type = "toggle", label = "MOUNTS MENU", default = true, description = "Enables M to cycle the eligible party mount for the active ride type." },
  { key = "mountShowFollowers", type = "toggle", label = "SHOW FOLLOWERS MOUNTED", default = false, description = "Keep party followers visible while riding. OFF reserves the mounted presentation for the rider and mount." },
  { key = "mountSoundRumble", type = "toggle", label = "SOUND & RUMBLE", default = true, description = "Allows mount feedback effects when supported by the host/controller." },
  { key = "mountVerticalSpeed", type = "choice", label = "VERTICAL SPEED", default = "normal", choices = { {"SLOW","slow"},{"NORMAL","normal"},{"FAST","fast"} }, description = "How quickly manual altitude changes." },
  { key = "mountAltitudeDisplay", type = "choice", label = "ALTITUDE DISPLAY", default = "flight", choices = { {"FLIGHT ONLY","flight"},{"ALWAYS","always"},{"OFF","off"} }, description = "Controls the altitude readout." },
  { key = "mountFlightBoost", type = "toggle", label = "FLIGHT BOOST", default = true, description = "Hold Shift while flying for a temporary high-speed cruise boost." },
  { key = "mountCameraFollow", type = "toggle", label = "CAMERA FOLLOW", default = true, description = "Allows the active 1ST/3RD camera provider to keep following mounted travel." },
  { key = "mountCameraAltitude", type = "toggle", label = "CAMERA ALTITUDE", default = true, description = "Lets third-person mounted framing follow vertical flight movement." },
  { key = "mountLandingMarker", type = "toggle", label = "LANDING MARKER", default = true, description = "Keeps landing safety validation active and exposes landing status in the mount HUD." },
  { key = "mountDynamicShadow", type = "toggle", label = "DYNAMIC SHADOW", default = true, description = "Keeps the mount in the voxel shadow pass while altitude changes." },
  { key = "mountAirEncounters", type = "toggle", label = "AIR ENCOUNTERS", default = false, description = "Flying into a visible roaming Pokemon can start its normal Gold wild battle." },
  { key = "ambientFlyingPokemon", type = "toggle", label = "AMBIENT SKY POKéMON", default = true, description = "Adds a small number of peaceful, render-only flying Pokémon to outdoor skies. Species are chosen from the current/neighboring encounter tables first, then from conservative forest/coast/mountain/town/time-of-day pools so they fit the location instead of spawning completely at random." },
  { key = "ambientFlyingDensity", type = "choice", label = "SKY POKéMON DENSITY", default = "normal", choices = { {"LOW","low"},{"NORMAL","normal"},{"HIGH","high"} }, description = "Controls how many ambient flying Pokémon are visible at once. NORMAL is intentionally light (usually 2, sometimes 3 on large outdoor maps) and their shadows are disabled to keep the voxel renderer cheap." },
  { key = "mountShortcut", type = "toggle", label = "KEYBOARD MOUNT SHORTCUTS", default = true, description = "H toggles Flight and G/J toggles Ground Ride while the idle overworld owns input. While flying, controller LAND uses Circle/B (the selected layout cancel button); all other face/menu buttons are quarantined from Gold until Flight ends." },
  { key = "mountControllerShortcuts", type = "toggle", label = "CONTROLLER MOUNT SHORTCUTS", default = false, description = "OFF (recommended) leaves controller face buttons entirely to normal menu/battle navigation while grounded. ON polls west-face (PlayStation Square / Xbox X / Switch Y) to start/toggle Flight and north-face (Triangle / Y / X) to toggle Ground Ride during idle free roam. Once airborne, those face buttons are quarantined and Circle/B is the only controller LAND action." },
  { key = "mountGroundGallop", type = "toggle", label = "GROUND GALLOP", default = true, description = "Hold Shift for a faster ground gallop with a rechargeable stamina meter." },
  { key = "mountGallopHud", type = "toggle", label = "GALLOP HUD", default = true, description = "Shows Ground Ride gallop stamina while mounted." },
  { key = "mountGroundDust", type = "toggle", label = "GROUND DUST", default = true, description = "Enables ground-motion feedback for mounted travel." },
  { key = "mountTwoWayLedges", type = "toggle", label = "TWO-WAY LEDGES", default = true, description = "Ground mounts can hop ledges in the reverse direction when the opposite ledge geometry is valid and the landing cell is safe." },
  { key = "mountRemountAfterBattle", type = "toggle", label = "REMOUNT AFTER BATTLE", default = true, description = "Preserves the selected ground mount across normal battle interruptions." },
  { key = "mountRequireFly", type = "toggle", label = "REQUIRE FLY MOVE", default = true, description = "ON requires the selected flying Pokemon to actually know FLY. OFF lets supported flying species take off without learning the move." },
  { key = "mountRequireSurf", type = "toggle", label = "REQUIRE SURF MOVE", default = true, description = "ON requires the selected swimming Pokemon to actually know SURF. OFF lets supported swimming species enter water without learning the move." },
  { key = "mountBadgeChecks", type = "toggle", label = "REQUIRE BADGES", default = true, description = "ON requires STORMBADGE for Flight and FOGBADGE for Swim/Surf. OFF bypasses those badge requirements for mounted traversal." },
  { key = "mountStoryGates", type = "toggle", label = "STORY GATES", default = true, description = "Prevents takeoff in indoor/cave-style environments and keeps authored route boundaries meaningful." },
  { key = "mountQuestCollisions", type = "toggle", label = "QUEST COLLISIONS", default = true, description = "Landing still respects walkability, warps and occupied cells instead of bypassing quest-sensitive ground geometry." },
  { key = "mountRenderer", type = "choice", label = "MOUNT RENDERER", default = "auto", choices = { {"AUTO","auto"},{"2D SPRITE","2d"},{"STADIUM 3D","stadium"} }, description = "AUTO uses Stadium 2 models when available in voxel mode and otherwise the active follower sprite. v0.3.08 no longer requires a 2D follower sheet before creating a Stadium mount, so valid imported 3D Pokemon can render directly beneath the rider. 2D forces sprite presentation; STADIUM requests the imported model path." },
  { key = "mountFlyingMusic", type = "choice", label = "FLYING MUSIC", default = "map", choices = { {"KEEP MAP MUSIC","map"},{"NONE / QUIET","none"} }, description = "Keeps normal map music during Flight or leaves flight-specific music disabled. No external copyrighted track is bundled." },
  { key = "mountSizeOverrides", type = "choice", label = "SIZE OVERRIDES", default = "hidden", choices = { {"HIDDEN","hidden"},{"EDIT","edit"} }, description = "EDIT reveals per-species mount scale percentages below in Advanced view." },
  {
    key = "partyFollower",
    type = "toggle",
    label = "LEAD PARTY FOLLOWER",
    default = true,
    description = "Makes the selected party slot follow directly behind the player. Slot 1 is the default, so using Gold's PARTY -> SWITCH command immediately changes the follower to the new top-of-party leader instead of keeping the original starter. Explicit FOLLOW selections can bind another party slot. The embedded Wilds trailer mover owns map/zone handoff; the native Gen-2 follower is suppressed to prevent duplicates. The follower uses its Stadium 2 3D model in voxel mode. Turn OFF to remove party followers.",
  },
  {
    key = "stadiumBattleAnimations",
    type = "toggle",
    label = "STADIUM ATTACK ANIMATIONS",
    default = true,
    description = "Keeps imported Stadium 2 skeletal attack animations active during live 3D battles. Turn OFF only for troubleshooting; ON is the normal/default behavior and still leaves Gold authoritative for damage, HP, PP and battle logic.",
  },
  {
    key = "stadiumFxPortEnabled",
    type = "toggle",
    label = "STADIUM BATTLE FX 2.1.7",
    default = true,
    description = "Master switch for the StadiumBattleFX 2.1.7 presentation port: source-calibrated move timing/programs, attack cameras, hit/faint presentation, optional Stadium 1 boss rooms/portraits, and announcer routing. Gold and this mod's Stadium 2 renderer remain the battle/model owners.",
  },
  {
    key = "stadiumFx2DLayer",
    type = "choice",
    label = "STADIUM CARTRIDGE FX",
    default = "authentic",
    choices = { { "AUTHENTIC ONLY", "authentic" }, { "ALL 165", "all" }, { "OFF", "off" } },
    description = "AUTHENTIC ONLY overlays the source's cartridge-calibrated prominent-move programs when available; ALL 165 also enables its deterministic generic renderer for the full Gen-1 move roster; OFF keeps only this mod's world-space 3D effects. A privately imported Pokemon Stadium (USA) v1.0 ROM unlocks the ROM-derived textures; no ROM data is bundled.",
  },
  {
    key = "stadiumFxNativeScheduler",
    type = "toggle",
    label = "STADIUM NATIVE SCHEDULER",
    default = true,
    description = "Runs StadiumBattleFX 2.1.7's exact native scheduler emissions and dedicated traced renderers (including Thunder Shock, Thunder Wave, Scratch, Sand Attack, Quick Attack, Gust, Horn, Leer, String Shot, Confusion, kick and tackle families). OFF keeps the lightweight cartridge/generic overlay path without the exact native scheduler.",
  },
  {
    key = "stadiumFxNativeSync",
    type = "toggle",
    label = "NATIVE ATTACH / CAMERA SYNC",
    default = true,
    description = "When a privately supplied Pokemon Stadium US 1.0 ROM is available, builds the source DSM7 metadata cache and uses its 151x165 species/move attachment bytes plus native camera selectors/cut timing. Gen-2-only Pokemon safely use the existing Stadium2 fallback.",
  },
  {
    key = "stadiumFxFallbackNotice",
    type = "toggle",
    label = "STADIUM FX FALLBACK NOTICE",
    default = true,
    description = "Shows the uploaded mod's short on-screen diagnostic if a source Stadium effect fails and safely falls back. Turn OFF to keep failures log-only.",
  },
  {
    key = "stadiumFxScreenEffects",
    type = "toggle",
    label = "STADIUM SCREEN WASH",
    default = true,
    description = "Adds the source-timed whole-frame flashes, color washes and field emphasis for screen-filling attacks. This is separate from the cartridge-effect layer and can be disabled if you prefer only world-space effects.",
  },
  {
    key = "stadiumFxAttackCamera",
    type = "toggle",
    label = "STADIUM ATTACK CAMERA FX",
    default = true,
    description = "Uses StadiumBattleFX's windup/travel/impact/recovery camera profiles on top of the existing live Stadium battle camera. Manual camera control still takes priority.",
  },
  {
    key = "stadiumFxAttackSpeed",
    type = "choice",
    label = "STADIUM ATTACK SPEED",
    default = "100",
    choices = {
      { "100%", "100" }, { "90%", "90" }, { "80%", "80" }, { "70%", "70" },
      { "60%", "60" }, { "50%", "50" }, { "40%", "40" }, { "30%", "30" },
      { "20%", "20" }, { "10%", "10" }, { "0% / OFF", "0" },
    },
    description = "Scales StadiumBattleFX move timing, source effect lifetime and attack-camera staging together. 0% disables the source-timed attack presentation while leaving Gold's ordinary battle presentation available.",
  },
  {
    key = "stadiumFxCinematicZoom",
    type = "choice",
    label = "ATTACK CAMERA WIDTH",
    default = "25",
    choices = { { "OFF", "off" }, { "10%", "10" }, { "25%", "25" }, { "35%", "35" }, { "50%", "50" } },
    description = "Extra safety width for the StadiumBattleFX attack camera. Higher values frame more of the arena during aerial, field and explosive moves.",
  },
  {
    key = "stadiumFxHitReactions",
    type = "toggle",
    label = "STADIUM HIT REACTIONS",
    default = true,
    description = "Lets real Gold HP loss trigger the Stadium 2 model's visual recoil plus the modern render-only knockback layer. OFF removes those hit reactions without changing damage.",
  },
  {
    key = "stadiumFxFaintAnimations",
    type = "toggle",
    label = "STADIUM FAINT ANIMATIONS",
    default = true,
    description = "Uses the imported Stadium skeletal faint performance when available. OFF leaves Gold/the normal model lifecycle to handle fainting.",
  },
  {
    key = "stadiumBossArenas",
    type = "toggle",
    label = "STADIUM BOSS ARENAS",
    default = true,
    description = "Uses ROM-derived Pokemon Stadium Gym Leader Castle / Elite Four / Champion rooms for compatible boss battles when a valid private Stadium 1 cache exists. Ordinary battles still use this mod's live overworld arena.",
  },
  {
    key = "stadiumTrainerPortraits",
    type = "toggle",
    label = "STADIUM TRAINER PORTRAITS",
    default = true,
    description = "Replaces compatible battle-opening trainer art with Pokemon Stadium's locally extracted 64x64 portraits when a valid private Stadium 1 cache is available. Unsupported Johto classes keep Gold's normal art.",
  },
  {
    key = "stadiumAnnouncer",
    type = "toggle",
    label = "STADIUM ANNOUNCER",
    default = true,
    description = "Enables the ported Stadium announcer event/timing engine. On PC or Android, choose your legally obtained Pokemon Stadium (USA) v1.0 ROM from STADIUM 1 / 2 ROM FILE; v0.4.22 locally builds the private 823-WAV voice cache and uses a sandbox-safe in-memory WAV/SoundData playback path on both platforms. No voice recordings are bundled. Use TEST STADIUM ANNOUNCER after import for an immediate voice check; captions also work without audio.",
  },
  {
    key = "stadiumAnnouncerScope",
    type = "choice",
    label = "ANNOUNCER BATTLES",
    default = "gym",
    choices = { { "GYM / ELITE 4 / CHAMPION", "gym" }, { "ALL TRAINER BATTLES", "trainer" }, { "ALL BATTLES", "all" } },
    description = "Chooses where announcer calls/captions are eligible. Source voice clips cover Stadium's original supported roster; Gold-only classes safely fall back to captions or silence when no matching clip exists.",
  },
  {
    key = "stadiumAnnouncerCaptions",
    type = "toggle",
    label = "ANNOUNCER CAPTIONS",
    default = true,
    description = "Shows Stadium-style battle call captions for introductions, move use, critical/effectiveness reactions, status, faint and victory. Useful when no private voice pack is installed.",
  },
  {
    key = "battleModernMotion",
    type = "toggle",
    label = "MODERN LIVE BATTLE MOTION",
    default = true,
    description = "Adds presentation-only contact lunges, damage knockback, movement commitment and camera impact to LIVE OVERWORLD BATTLES. Gold still owns the real turn, damage, HP, PP, status and outcome logic.",
  },
  {
    key = "battleMovementFeel",
    type = "choice",
    label = "BATTLE MOVEMENT FEEL",
    default = "modern",
    choices = { { "TIGHT", "tight" }, { "MODERN", "modern" }, { "SMOOTH", "smooth" } },
    description = "Changes left-stick/WASD acceleration and stopping for direct Pokemon movement in live 3D battles. TIGHT reacts fastest, MODERN is balanced, SMOOTH has heavier momentum.",
  },
  {
    key = "battleImpactFeedback",
    type = "choice",
    label = "BATTLE IMPACT FEEDBACK",
    default = "normal",
    choices = { { "LOW", "low" }, { "NORMAL", "normal" }, { "HIGH", "high" } },
    description = "Controls presentation-only hit knockback, camera shake and impact zoom strength. It never changes move power or damage.",
  },
  {
    key = "battleBackgroundFile",
    type = "choice",
    label = "2D BATTLE BACKGROUND",
    default = "choose",
    choices = {
      { "CHOOSE", "choose" },
    },
    description = "Custom image behind Gold's native 2D battle sprites in the classic battle scene. A/Confirm or Right opens the PC/Android file picker for PNG, JPEG, or BMP images; Left restores Gold's default white background. LIVE OVERWORLD BATTLES keeps the voxel encounter world instead, so turn that option OFF when you want this custom 2D background to be visible.",
  },
  {
    key = "transparentBattleUI",
    type = "toggle",
    label = "TRANSPARENT BATTLE UI BG",
    default = true,
    description = "ON (default): removes Gold's opaque white paper fills behind the battle HUD, HP/name areas, message box and command boxes so the live voxel world or your custom 2D battle image stays visible behind the UI. Borders, text, HP bars, Pokemon/models and battle effects are preserved. OFF restores the normal white cartridge-style UI background.",
  },
  {
    key = "battle3dWorld",
    type = "toggle",
    label = "LIVE OVERWORLD BATTLES",
    default = true,
    description = "ON (default): ordinary wild battles stay in the exact voxel overworld view where the encounter began, using the same map, camera, weather and terrain while Gold keeps its native battle UI and logic. OFF: use Gold's classic battle scene. This can be changed without uninstalling the mod.",
  },
  {
    key = "doubleBattleMode",
    type = "toggle",
    label = "DOUBLE BATTLE MODE",
    default = false,
    description = "Custom Stadium duo mode for Pokemon Gold. OFF keeps Gold's native one-Pokemon battle rules. ON uses the first two healthy, non-EGG Pokemon in party order as your battle duo. FIGHT always waits for two distinct choices: pick Pokemon #1's move, then explicitly pick Pokemon #2's move; the second attack is never auto-selected unless STRUGGLE is the only legal action. While each move list is active, left stick/WASD moves only that currently selected Pokemon and the other stays in place. Gold still owns HP, PP, status, fainting, EXP, catching, switching and battle completion.",
  },
  {
    key = "battleSmartCamera",
    type = "toggle",
    label = "STADIUM BATTLE CAMERA",
    default = true,
    description = "ON (default): LIVE OVERWORLD BATTLES use a cinematic Pokemon Stadium-style camera that smoothly orbits both Pokemon, pushes in during attack animations, and temporarily yields to manual right-thumb/mouse camera control before resuming. OFF keeps the encounter-world camera static/manual.",
  },
  {
    key = "battleCommands",
    type = "toggle",
    label = "BATTLE COMMANDS",
    default = true,
    description = "Chooses the battle UI. ON uses this mod's custom Stadium battle HUD and FIGHT / PKMN / PACK / RUN commands. OFF restores Gold's original Gen-2 battle UI and native battle-menu input, including its original command box, move menu, PACK and PKMN flow.",
  },
  {
    key = "battleShortcutMode",
    type = "choice",
    label = "BATTLE HUD SHORTCUTS",
    default = "face",
    choices = {
      { "FACE BUTTONS", "face" },
      { "D-PAD / ARROWS", "dpad" },
      { "NATIVE / OFF", "native" },
    },
    description = "Remaps or disables the custom battle-command shortcuts while keeping the Stadium HUD. FACE BUTTONS uses the four physical face-button positions: left=FIGHT, top=PKMN, bottom=PACK, right=RUN; the visible button names follow CONTROLLER LAYOUT (PlayStation / Xbox / Switch). D-PAD / ARROWS moves the direct commands to the D-pad/arrow directions and leaves face buttons to Gold. NATIVE / OFF disables direct shortcuts entirely and lets Gold's normal menu input handle commands. All modes automatically yield every button to Gold while battle text/messages are being advanced.",
  },
  {
    key = "weatherMode",
    type = "choice",
    label = "WEATHER FX",
    default = "auto",
    choices = {
      { "OFF", "off" }, { "AUTO", "auto" }, { "CYCLE / SHOWCASE", "cycle" },
      { "CLEAR", "CLEAR" }, { "SUN", "SUNNY" }, { "HEATWAVE", "HEATWAVE" },
      { "HARSH SUN", "HARSH_SUN" }, { "RAIN", "RAIN_LIGHT" },
      { "HEAVY RAIN", "RAIN_HEAVY" }, { "PRIMAL RAIN", "HEAVY_RAIN" },
      { "THUNDERSTORM", "STORM" }, { "GALE", "GALE" },
      { "SNOW", "SNOW_LIGHT" }, { "BLIZZARD", "BLIZZARD" },
      { "HAIL", "HAIL" }, { "SLEET", "SLEET" },
      { "THUNDERSNOW", "THUNDERSNOW" }, { "SANDSTORM", "SANDSTORM" },
      { "DUST STORM", "DUSTSTORM" }, { "ASHFALL", "ASHFALL" },
      { "STRONG WINDS", "STRONG_WINDS" }, { "FLOCK STORM", "FLOCKSTORM" },
      { "SWARM", "SWARM" }, { "HAUNTED MIST", "HAUNTED_MIST" },
      { "DRAGON STORM", "DRAGONSTORM" }, { "BRAWL WIND", "BRAWL_WIND" },
      { "PLAIN FRONT", "PLAIN_FRONT" }, { "VERDANT RAIN", "VERDANT_RAIN" },
      { "SMOG", "SMOG" }, { "FOG", "FOG" }, { "PSY STORM", "PSYSTORM" },
    },
    description = "Weather FX 4.10 replaces this mod's old rain/fog/cloud effects. AUTO runs location-aware regional fronts and changing spells; CYCLE showcases every weather; named conditions now apply immediately on the next fixed tick. OFF also shuts down the 3D atmosphere.",
  },
  {
    key = "quality", type = "choice", label = "WX QUALITY", default = "auto",
    choices = { { "AUTO", "auto" }, { "HIGH", "high" }, { "MEDIUM", "medium" }, { "LOW", "low" } },
    description = "Weather FX particle/atmosphere budget. LOW also reduces Stadium2 volumetric atmosphere density; AUTO/HIGH use the full 3D atmosphere.",
  },
  {
    key = "intensity", type = "choice", label = "WX INTENSITY", default = "normal",
    choices = { { "SOFT", "soft" }, { "NORMAL", "normal" }, { "HEAVY", "heavy" }, { "AUTO", "auto" } },
    description = "Overall Weather FX strength for both 2D and Stadium2 3D weather. AUTO lets the eased Weather FX channels breathe naturally while the 3D cloud field stays stable.",
  },
  {
    key = "exotic", type = "choice", label = "RARE WEATHER", default = "normal",
    choices = { { "OFF", "off" }, { "RARE", "rare" }, { "NORMAL", "normal" }, { "OFTEN", "often" } },
    description = "How often unusual snow, hail, sleet, sand and ash conditions appear away from their most natural locations.",
  },
  {
    key = "speed", type = "choice", label = "WX AUTO SPEED", default = "normal",
    choices = { { "SLOW", "slow" }, { "NORMAL", "normal" }, { "FAST", "fast" }, { "TEST", "test" } },
    description = "How long automatic weather spells last. TEST changes quickly for previewing effects.",
  },
  {
    key = "daytime", type = "choice", label = "WX TIME WEIGHT", default = "on",
    choices = { { "ON", "on" }, { "OFF", "off" } },
    description = "Lets the Gold day/night clock influence automatic weather, such as more fog and storms after dark.",
  },
  {
    key = "seasons", type = "choice", label = "WX SEASONS", default = "on",
    choices = { { "ON", "on" }, { "OFF", "off" } },
    description = "Weather FX seasons bias automatic conditions, including more snow in winter and sun in summer.",
  },
  {
    key = "hemisphere", type = "choice", label = "WX HEMISPHERE", default = "northern",
    choices = { { "NORTH", "northern" }, { "SOUTH", "southern" } },
    description = "Season orientation for Weather FX.",
  },
  {
    key = "seasonNotify", type = "choice", label = "SEASON NOTE", default = "on",
    choices = { { "ON", "on" }, { "OFF", "off" } },
    description = "Shows Weather FX season-change notifications.",
  },
  {
    key = "lightning", type = "choice", label = "LIGHTNING", default = "full",
    choices = { { "OFF", "off" }, { "SOFT", "soft" }, { "FULL", "full" } },
    description = "Weather FX lightning. SOFT avoids sharp full-screen flashes while keeping storm glow.",
  },
  {
    key = "sfx", type = "choice", label = "WEATHER SFX", default = "medium",
    choices = { { "OFF", "off" }, { "LOW", "low" }, { "MEDIUM", "medium" }, { "HIGH", "high" } },
    description = "Weather FX rain, thunder and wind audio mixed under the game's music.",
  },
  {
    key = "splash", type = "choice", label = "RAIN SPLASHES", default = "on",
    choices = { { "ON", "on" }, { "OFF", "off" } },
    description = "Rain drops create Weather FX landing splashes.",
  },
  {
    key = "indoors", type = "choice", label = "INDOOR WEATHER", default = "tint",
    choices = { { "OFF", "off" }, { "TINT", "tint" } },
    description = "TINT keeps storm gloom/lightning ambience indoors without making precipitation fall through roofs.",
  },
  {
    key = "present", type = "choice", label = "WX PRESENT", default = "auto",
    choices = { { "AUTO", "auto" }, { "3D", "3d" }, { "2D", "2d" } },
    description = "AUTO/3D uses Weather FX's Stadium2 voxel atmosphere for world-space clouds, rain and fog when available. 2D forces its original screen-space effects.",
  },
  {
    key = "debugRain", type = "choice", label = "DEBUG RAIN", default = "off",
    choices = { { "OFF", "off" }, { "ON", "on" } },
    description = "For diagnostics: forces Weather FX heavy-rain state. Leave OFF for normal play.",
  },
  {
    key = "stadiumRomFile",
    type = "choice",
    label = "STADIUM 1 / 2 ROM FILE",
    default = "choose",
    choices = {
      { "CHOOSE", "choose" },
    },
    description = "Uses the normal platform file picker (desktop on PC, system Files picker on Android). Choose Pokemon Stadium 2 to build the 001-251 3D model/world cache, or Pokemon Stadium (USA) v1.0 to build StadiumBattleFX data plus the private 823-clip announcer cache. You can open this same row again to import the other ROM.",
  },
  -- ------- Core gameplay
  {
    key = "enabled",
    label = "Show Wild Mons",
    type = "toggle",
    default = true,
    description = "Spawn visible wild Pokemon in eligible overworld encounter areas.",
  },
  {
    key = "sprite_style",
    label = "Sprite Style",
    type = "choice",
    default = "followers",
    choices = {
      { "Poke Followers / GSC", "followers" },
      { "HGSS / PokeMMO", "pokemmo" },
      { "Pokédex", "pokedex" },
    },
    description = "Overworld sprite style for wild Pokémon and followers. Poke Followers / GSC is the built-in default. Water Pokémon still use Swimming or Levitates sprites when available.",
  },
  {
    key = "sprite_fade",
    label = "Sprite Fade",
    type = "choice",
    default = "solid",
    choices = {
      { "Solid", "solid" },
      { "Faded", "faded" },
    },
    description = "Opacity of normal visible wild Pokémon. Solid is fully opaque. Faded uses the classic semi-transparent wild look. Does not affect followers, Town Pokémon, silhouettes, or UI.",
  },
  {
    key = "follow_control",
    label = "Control Mode",
    type = "choice",
    default = "trainer",
    choices = {
      { "Trainer", "trainer" },
      { "Pokémon", "pokemon" },
    },
    description = "Choose whether you control the trainer or the selected Pokémon.",
  },
  {
    key = "trainer_trail",
    label = "Trainer Trail",
    type = "toggle",
    default = false,
    description = "When controlling a Pokémon, the trainer follows behind.",
  },
  {
    key = "follower_count",
    label = "Followers",
    type = "choice",
    default = 1,
    choices = {
      { "0", 0 },
      { "1", 1 },
      { "2", 2 },
      { "3", 3 },
      { "4", 4 },
      { "5", 5 },
      { "6", 6 },
    },
    description = "Number of additional party Pokémon following the active leader.",
  },
  {
    key = "follower_player_spacing",
    label = "Player-Follower Gap",
    type = "choice",
    default = 1,
    choices = {
      { "1 Tile", 1 }, { "2 Tiles", 2 }, { "3 Tiles", 3 }, { "4 Tiles", 4 },
    },
    description = "How many walked tiles the first follower stays behind the player. The gap follows your actual path around corners instead of using straight-line teleport spacing.",
  },
  {
    key = "follower_pokemon_spacing",
    label = "Pokemon-Pokemon Gap",
    type = "choice",
    default = 1,
    choices = {
      { "1 Tile", 1 }, { "2 Tiles", 2 }, { "3 Tiles", 3 }, { "4 Tiles", 4 },
    },
    description = "Additional walked-tile gap between each Pokemon in a multi-follower line.",
  },
  {
    key = "spawn_density",
    label = "Spawn Amount",
    type = "choice",
    default = "normal",
    choices = {
      { "Low", "low" },
      { "Normal", "normal" },
      { "High", "high" },
      { "Very High", "very_high" },
    },
    description = "Controls how many visible overworld Pokémon can appear. This also affects visible water Pokémon.",
  },
  {
    key = "random_encounters",
    label = "Classic Step Enc",
    type = "toggle",
    default = false,
    description = "OFF is visible-only mode: roaming Pokemon in Gold/Kanto can still start battles when you touch/interact with them, but invisible grass/cave step rolls are blocked. ON additionally enables classic random steps; while visiting Kanto those rolls use Pokemon Yellow's original map encounter rate, weighted slots, species and levels, then launch the fight through Gold's battle runtime.",
  },
  {
    key = "water_spawns",
    label = "Water Mons",
    type = "choice",
    default = "swimming_sprites",
    choices = {
      { "Swim Sprites", "swimming_sprites" },
      { "Hid Silhouette", "hidden_silhouettes" },
      { "Silhouettes", "silhouettes" },
      { "Classic Enc", "classic_encounters" },
      { "Disabled", "disabled" },
    },
    description = "How water Pokémon appear: swimming sprites (default), hidden dark circles, tinted silhouettes, classic random encounters only, or fully disabled.",
  },
  {
    key = "cave_spawns",
    label = "Cave Spawns",
    type = "choice",
    default = "reachable",
    choices = {
      { "Reachable Only", "reachable" },
      { "Mixed", "mixed" },
    },
    description = "Cave Pokémon spawn only on tiles the player can reach, or Mixed (~20% atmospheric scenery in inaccessible cave pockets).",
  },
  {
    key = "town_pokemon",
    label = "Town Pokémon",
    type = "toggle",
    default = true,
    description = "Adds peaceful Pokémon to safe towns and interiors. They behave like NPCs and cannot start battles.",
  },
  {
    key = "pokemon_grass_render_mode",
    label = "Grass View",
    type = "choice",
    default = "immersed",
    choices = {
      { "Above", "above" },
      { "Immersed", "immersed" },
    },
    description = "Draw wild Pokemon fully above tall grass, or partially hidden inside it like the player and trainers.",
  },
  {
    key = "wild_silhouettes",
    label = "Enc Silhouette",
    type = "toggle",
    default = false,
    description = "Black out overworld wild Pokémon in encounter zones (grass/cave/water) as silhouettes, keeping their shapes. Derived from the coloured art at load — no extra sprite files.",
  },
  {
    key = "enable_idle",
    label = "Idle Mons",
    type = "toggle",
    default = true,
    description = "Allow Idle Look behaviour (stand still, glance around).",
  },
  {
    key = "enable_wander",
    label = "Roam Mons",
    type = "toggle",
    default = true,
    description = "Allow wander behaviour within a connected encounter region.",
  },
  {
    key = "enable_aggressive",
    label = "Chase Mons",
    type = "toggle",
    default = true,
    description = "Allow aggressive Pokemon that spot, chase, and force a battle.",
  },
  {
    key = "enable_hidden",
    label = "Hidden Mons",
    type = "toggle",
    default = false,
    description = "Disabled for Gold/Silver visible-roaming mode; encounter Pokemon are shown on the map.",
  },

  -- ------- Developer (only Dev Overlay + Test Spawn)
  {
    key = "dev_overlay",
    label = "Dev Overlay",
    type = "toggle",
    default = false,
    description = "Shows each wild Pokémon's behaviour and facing direction above it.",
  },
}

-- Per-species mount sizing is generated so every supported Flight/Ground/Surf
-- mount can be tuned without hand-editing files. The categorized Mod Settings
-- browser hides these rows until ADVANCED + SIZE OVERRIDES=EDIT.
local mountSizeSpecies = {
  "CHARIZARD",
  "PIDGEOT",
  "FEAROW",
  "GOLBAT",
  "AERODACTYL",
  "ARTICUNO",
  "ZAPDOS",
  "MOLTRES",
  "DRAGONAIR",
  "DRAGONITE",
  "NOCTOWL",
  "CROBAT",
  "XATU",
  "SKARMORY",
  "LUGIA",
  "HO_OH",
  "ARCANINE",
  "RAPIDASH",
  "DODRIO",
  "RHYHORN",
  "RHYDON",
  "KANGASKHAN",
  "TAUROS",
  "SNORLAX",
  "MEGANIUM",
  "GIRAFARIG",
  "URSARING",
  "DONPHAN",
  "STANTLER",
  "RAIKOU",
  "ENTEI",
  "SUICUNE",
  "TYRANITAR",
  "BLASTOISE",
  "TENTACRUEL",
  "GYARADOS",
  "LAPRAS",
  "FERALIGATR",
  "MANTINE",
  "KINGDRA",
}
for _, species in ipairs(mountSizeSpecies) do
  schema[#schema + 1] = {
    key = "mountSize_" .. species:lower(), type = "number",
    label = species:gsub("_", " ") .. " SIZE %",
    default = 100, min = 50, max = 200, step = 5,
    description = "Per-species Fly Your Pokemon mount scale override."
  }
end

return schema
