-- Options for Pokemon Stadium 2 Overworld Models - Gold/Silver (Gen 2).
-- Includes the embedded Wilds of Kanto roaming-spawn controls so this ZIP is standalone.
return {
  {
    key = "voxel3d",
    type = "toggle",
    label = "3D VOXEL WORLD",
    default = true,
    description = "Enables the Gold Gen-2 voxel world. v0.2.80 restores full-color 2D Pokemon/follower art in Gold while v0.2.79 adds DSM7 tile-origin/eye-mirror recovery on top of the DSM6 Stadium material fix and National-number Pokédex ordering while v0.2.77 keeps the Gold voxel/Character Selector and Wilds sandbox recovery, preserves automatic battle startup/follower handoff, adds matching translucent dialogue/YES-NO boxes, extends OPEN WORLD zoom-out range, keeps the battle-command text lanes fixed, and auto-fits full Stadium models inside tall Pokédex previews. Platform and file checks use engine/mod-owned compatibility seams. Native TILT OFF uses the normal 35-degree voxel diorama; TILT 15/35/50 remain literal. Turn this switch OFF to return to Gold's real 2D overworld. Stadium 2 ROM selection is not required for terrain.",
  },
  {
    key = "customUI",
    type = "toggle",
    label = "CUSTOM UI / MENUS",
    default = true,
    description = "ON uses this mod's custom translucent Stadium-style pause menu, Pokedex/Party/Pack/Pokegear/Trainer/Save/Options screens, custom Mod Manager presentation and custom live-battle HUD. OFF hands those screens back to Gold/Gen1Recomp's original menu renderers and native battle UI while leaving voxel terrain, OPEN WORLD, weather, models and other non-UI features enabled. The direct MOD SETTINGS pause shortcut is also hidden while OFF; use MODS > this mod > OPTIONS to turn it back ON.",
  },
  {
    key = "stadium3dSprites",
    type = "toggle",
    label = "3D POKéMON MODELS",
    default = true,
    description = "Controls Pokemon models only. ON uses Stadium 2 3D models for roaming/wild Pokemon, the party follower, live-battle combatants and custom Pokedex/Party/battle previews. OFF keeps the voxel terrain, 3D scenery and OPEN WORLD renderer but returns Pokemon to their normal Gold 2D sprite/card presentation. The human player's 3D model is controlled separately below.",
  },
  {
    key = "player3dModel",
    type = "toggle",
    label = "3D PLAYER MODEL",
    default = true,
    description = "Controls the human player model only. ON allows red_3d_player / 3D Character Selector to draw the currently selected 3D player skin inside the voxel world. OFF forces the player back to Gold's normal 2D trainer sprite/card while leaving Stadium Pokemon models, followers, battles, Pokedex previews, voxel terrain and OPEN WORLD untouched.",
  },
  {
    key = "openWorld",
    type = "toggle",
    label = "OPEN WORLD",
    default = false,
    description = "OFF (default) keeps the performance-friendly 3D streamer: current Gold map + directly connected neighbours. ON is a true OPEN WORLD 3D mode: it keeps the voxel provider active, loads the full cardinally connected outdoor graph, builds every map as full voxel terrain with internal seams masked, keeps the outside voxel border/apron so a world-scale view has no empty void around the stitched region, and preserves all normal 3D trees/buildings/props, tall grass/flowers, NPCs, roaming Pokemon and Stadium models. Distant maps appear as their voxel meshes finish instead of forcing the whole screen back to flat 2D. This can use much more RAM/VRAM/CPU/GPU; switch OFF to return to normal streaming and release far meshes.",
  },
  {
    key = "voxelDiskCache",
    type = "toggle",
    label = "VOXEL DISK CACHE",
    default = false,
    description = "RECOVERY MODE: persistent voxel disk-cache reads/writes have been disabled since v0.2.64 because a cached terrain mesh was reproduced causing incomplete/misaligned world visuals. The normal in-memory mesh cache still works. This switch is kept for settings compatibility but persistent cache I/O will remain off until the cache format is rebuilt safely.",
  },
  {
    key = "cameraControl",
    type = "choice",
    label = "CAMERA CONTROL",
    default = "auto",
    choices = {
      { "AUTO", "auto" },
      { "THIS MOD", "stadium" },
      { "CHARACTER SELECTOR", "selector" },
    },
    description = "AUTO gives red_3d_player / 3D Character Selector control of ZOOM, 1ST and 3RD camera modes when that mod is installed; otherwise this mod controls the camera. THIS MOD always uses the 3D CAMERA MODE option below. CHARACTER SELECTOR explicitly follows the engine voxel camera level and leaves the selector's Gen-2 movement controls untouched.",
  },
  {
    key = "cameraMode",
    type = "choice",
    label = "3D CAMERA MODE",
    default = "diorama",
    choices = {
      { "DIORAMA", "diorama" },
      { "THIRD PERSON", "third" },
      { "FIRST PERSON", "first" },
    },
    description = "Camera used by the voxel world. On Android, a 3-position in-game touch slider switches DIORAMA / THIRD PERSON / FIRST PERSON. On desktop, F6 cycles the same three modes. In THIRD/FIRST PERSON, mouse-look and a controller right stick both rotate the camera. When Character Selector owns the camera, the Android slider/F6 changes its public ZOOM / 3RD / 1ST voxel rung instead of overriding the selector.",
  },
  {
    key = "worldZoomRange",
    type = "choice",
    label = "OPEN WORLD ZOOM LIMIT",
    default = "world",
    choices = {
      { "STANDARD 2.2X", "standard" },
      { "FAR 4X", "far" },
      { "WORLD 8X", "world" },
      { "EXTREME 12X", "extreme" },
    },
    description = "Maximum DIORAMA camera distance available through wheel/trackpad/pinch zoom. STANDARD keeps the old 2.2x limit; FAR adds several wider survey steps; WORLD (default) reaches 8x for seeing a large connected OPEN WORLD region; EXTREME reaches 12x for very large stitched graphs. Startup remains 1x, so this only changes how far you may pull back. While OPEN WORLD is ON, FAR/WORLD/EXTREME also unlock one engine-native 0.25-scale survey rung for Character Selector/native ZOOM compatibility.",
  },
  {
    key = "cameraSlider",
    type = "toggle",
    label = "ANDROID CAMERA SLIDER",
    default = true,
    description = "Shows the DIORAMA / 3RD / 1ST touch slider at the top of the screen on Android. Turn this OFF to completely hide the slider and release its touch area for camera look/pinch gestures.",
  },
  {
    key = "screenFlip",
    type = "toggle",
    label = "FLIP SCREEN 180 DEGREES",
    default = false,
    description = "Android emergency reverse-landscape helper. Rotates the ENTIRE finished Gold game frame 180 degrees after all rendering, including voxel world, menus, battle UI, overlays and on-screen touch controls. Touch coordinates are remapped by the same 180-degree transform so buttons still line up. Use this as a compatibility workaround on Android devices that insist on the wrong landscape side.",
  },
  {
    key = "partyFollower",
    type = "toggle",
    label = "LEAD PARTY FOLLOWER",
    default = true,
    description = "Makes the selected party slot follow directly behind the player. Slot 1 is the default, so using Gold's PARTY -> SWITCH command immediately changes the follower to the new top-of-party leader instead of keeping the original starter. Explicit FOLLOW selections can bind another party slot. The embedded Wilds trailer mover owns map/zone handoff; the native Gen-2 follower is suppressed to prevent duplicates. The follower uses its Stadium 2 3D model in voxel mode. Turn OFF to remove party followers.",
  },
  {
    key = "battle3dWorld",
    type = "toggle",
    label = "LIVE OVERWORLD BATTLES",
    default = true,
    description = "ON (default): ordinary wild battles stay in the exact voxel overworld view where the encounter began, using the same map, camera, weather and terrain while Gold keeps its native battle UI and logic. OFF: use Gold's classic battle scene. This can be changed without uninstalling the mod.",
  },
  {
    key = "battleSmartCamera",
    type = "toggle",
    label = "STADIUM BATTLE CAMERA",
    default = true,
    description = "ON (default): LIVE OVERWORLD BATTLES use a cinematic Pokemon Stadium-style camera that smoothly orbits both Pokemon, pushes in during attack animations, and temporarily yields to manual right-thumb/mouse camera control before resuming. OFF keeps the encounter-world camera static/manual.",
  },
  {
    key = "battleCommands",
    type = "toggle",
    label = "BATTLE COMMANDS",
    default = true,
    description = "Chooses the battle UI. ON uses this mod's custom Stadium battle HUD and FIGHT / PKMN / PACK / RUN commands. OFF restores Gold's original Gen-2 battle UI and native battle-menu input, including its original command box, move menu, PACK and PKMN flow.",
  },
  {
    key = "battleShortcutMode",
    type = "choice",
    label = "BATTLE HUD SHORTCUTS",
    default = "face",
    choices = {
      { "FACE BUTTONS", "face" },
      { "D-PAD / ARROWS", "dpad" },
      { "NATIVE / OFF", "native" },
    },
    description = "Remaps or disables the custom battle-command shortcuts while keeping the Stadium HUD. FACE BUTTONS uses Square/Left=FIGHT, Triangle/Up=PKMN, Cross/Down=PACK, Circle/Right=RUN. D-PAD / ARROWS moves the direct commands to the D-pad/arrow directions and leaves face buttons to Gold. NATIVE / OFF disables direct shortcuts entirely and lets Gold's normal menu input handle commands. All modes automatically yield every button to Gold while battle text/messages are being advanced.",
  },
  {
    key = "weatherMode",
    type = "choice",
    label = "3D WEATHER",
    default = "auto",
    choices = {
      { "AUTO", "auto" },
      { "CLEAR", "clear" },
      { "RAIN", "rain" },
      { "FOG", "fog" },
      { "RAIN + FOG", "rain_fog" },
    },
    description = "Outdoor Gold voxel weather. AUTO slowly cycles conditions; the other choices force one. Interiors stay clear.",
  },
  {
    key = "weatherClouds",
    type = "toggle",
    label = "MOVING CLOUDS",
    default = true,
    description = "Moving pixel-cloud layers behind the 3D world. The existing day/night sky keeps the sun by day and moon by night.",
  },
  {
    key = "stadiumRomFile",
    type = "choice",
    label = "STADIUM 2 ROM FILE (GEN 2)",
    default = "choose",
    choices = {
      { "CHOOSE", "choose" },
    },
    description = "Choose your legally obtained Pokemon Stadium 2 ROM to build 3D models for National Dex 1-251.",
  },
  -- ------- Core gameplay
  {
    key = "enabled",
    label = "Show Wild Mons",
    type = "toggle",
    default = true,
    description = "Spawn visible wild Pokemon in eligible overworld encounter areas.",
  },
  {
    key = "sprite_style",
    label = "Sprite Style",
    type = "choice",
    default = "followers",
    choices = {
      { "Poke Followers / GSC", "followers" },
      { "HGSS / PokeMMO", "pokemmo" },
      { "Pokédex", "pokedex" },
    },
    description = "Overworld sprite style for wild Pokémon and followers. Poke Followers / GSC is the built-in default. Water Pokémon still use Swimming or Levitates sprites when available.",
  },
  {
    key = "sprite_fade",
    label = "Sprite Fade",
    type = "choice",
    default = "solid",
    choices = {
      { "Solid", "solid" },
      { "Faded", "faded" },
    },
    description = "Opacity of normal visible wild Pokémon. Solid is fully opaque. Faded uses the classic semi-transparent wild look. Does not affect followers, Town Pokémon, silhouettes, or UI.",
  },
  {
    key = "follow_control",
    label = "Control Mode",
    type = "choice",
    default = "trainer",
    choices = {
      { "Trainer", "trainer" },
      { "Pokémon", "pokemon" },
    },
    description = "Choose whether you control the trainer or the selected Pokémon.",
  },
  {
    key = "trainer_trail",
    label = "Trainer Trail",
    type = "toggle",
    default = false,
    description = "When controlling a Pokémon, the trainer follows behind.",
  },
  {
    key = "follower_count",
    label = "Followers",
    type = "choice",
    default = 1,
    choices = {
      { "0", 0 },
      { "1", 1 },
      { "2", 2 },
      { "3", 3 },
      { "4", 4 },
      { "5", 5 },
      { "6", 6 },
    },
    description = "Number of additional party Pokémon following the active leader.",
  },
  {
    key = "spawn_density",
    label = "Spawn Amount",
    type = "choice",
    default = "normal",
    choices = {
      { "Low", "low" },
      { "Normal", "normal" },
      { "High", "high" },
      { "Very High", "very_high" },
    },
    description = "Controls how many visible overworld Pokémon can appear. This also affects visible water Pokémon.",
  },
  {
    key = "random_encounters",
    label = "Classic Step Enc",
    type = "toggle",
    default = false,
    description = "OFF is the visible-only mode: normal grass/cave step encounters are blocked so every ordinary encounter comes from a Pokemon you can see and touch. Turn ON only if you also want classic invisible random steps.",
  },
  {
    key = "water_spawns",
    label = "Water Mons",
    type = "choice",
    default = "swimming_sprites",
    choices = {
      { "Swim Sprites", "swimming_sprites" },
      { "Hid Silhouette", "hidden_silhouettes" },
      { "Silhouettes", "silhouettes" },
      { "Classic Enc", "classic_encounters" },
      { "Disabled", "disabled" },
    },
    description = "How water Pokémon appear: swimming sprites (default), hidden dark circles, tinted silhouettes, classic random encounters only, or fully disabled.",
  },
  {
    key = "cave_spawns",
    label = "Cave Spawns",
    type = "choice",
    default = "reachable",
    choices = {
      { "Reachable Only", "reachable" },
      { "Mixed", "mixed" },
    },
    description = "Cave Pokémon spawn only on tiles the player can reach, or Mixed (~20% atmospheric scenery in inaccessible cave pockets).",
  },
  {
    key = "town_pokemon",
    label = "Town Pokémon",
    type = "toggle",
    default = true,
    description = "Adds peaceful Pokémon to safe towns and interiors. They behave like NPCs and cannot start battles.",
  },
  {
    key = "pokemon_grass_render_mode",
    label = "Grass View",
    type = "choice",
    default = "immersed",
    choices = {
      { "Above", "above" },
      { "Immersed", "immersed" },
    },
    description = "Draw wild Pokemon fully above tall grass, or partially hidden inside it like the player and trainers.",
  },
  {
    key = "wild_silhouettes",
    label = "Enc Silhouette",
    type = "toggle",
    default = false,
    description = "Black out overworld wild Pokémon in encounter zones (grass/cave/water) as silhouettes, keeping their shapes. Derived from the coloured art at load — no extra sprite files.",
  },
  {
    key = "enable_idle",
    label = "Idle Mons",
    type = "toggle",
    default = true,
    description = "Allow Idle Look behaviour (stand still, glance around).",
  },
  {
    key = "enable_wander",
    label = "Roam Mons",
    type = "toggle",
    default = true,
    description = "Allow wander behaviour within a connected encounter region.",
  },
  {
    key = "enable_aggressive",
    label = "Chase Mons",
    type = "toggle",
    default = true,
    description = "Allow aggressive Pokemon that spot, chase, and force a battle.",
  },
  {
    key = "enable_hidden",
    label = "Hidden Mons",
    type = "toggle",
    default = false,
    description = "Disabled for Gold/Silver visible-roaming mode; encounter Pokemon are shown on the map.",
  },

  -- ------- Developer (only Dev Overlay + Test Spawn)
  {
    key = "dev_overlay",
    label = "Dev Overlay",
    type = "toggle",
    default = false,
    description = "Shows each wild Pokémon's behaviour and facing direction above it.",
  },
}
