-- Generated from Kanto Reforged 1.2.0 species #152-386.
-- Loaded only after Weather FX detects the optional Kanto-Reforged mod.
local variants = {
  { n=301, id="WX_301_CHIKORITA_BLOOM", base="CHIKORITA", baseName="Chikorita", variant="BLOOM", types={ "GRASS", "FAIRY" }, weather="Spring Rain", cohort=3, rarity="rare", kantoReforged=true },
  { n=302, id="WX_302_BAYLEEF_BLOOM", base="BAYLEEF", baseName="Bayleef", variant="BLOOM", types={ "GRASS", "FAIRY" }, weather="Spring Rain", cohort=3, rarity="rare", kantoReforged=true },
  { n=303, id="WX_303_MEGANIUM_BLOOM", base="MEGANIUM", baseName="Meganium", variant="BLOOM", types={ "GRASS", "FAIRY" }, weather="Spring Rain", cohort=3, rarity="rare", kantoReforged=true },
  { n=304, id="WX_304_CYNDAQUIL_CINDER", base="CYNDAQUIL", baseName="Cyndaquil", variant="CINDER", types={ "FIRE", "GHOST" }, weather="Ashfall", cohort=3, rarity="rare", kantoReforged=true },
  { n=305, id="WX_305_QUILAVA_CINDER", base="QUILAVA", baseName="Quilava", variant="CINDER", types={ "FIRE", "GHOST" }, weather="Ashfall", cohort=3, rarity="rare", kantoReforged=true },
  { n=306, id="WX_306_TYPHLOSION_CINDER", base="TYPHLOSION", baseName="Typhlosion", variant="CINDER", types={ "FIRE", "GHOST" }, weather="Ashfall", cohort=3, rarity="rare", kantoReforged=true },
  { n=307, id="WX_307_TOTODILE_TEMPEST", base="TOTODILE", baseName="Totodile", variant="TEMPEST", types={ "WATER", "ELECTRIC" }, weather="Storm", cohort=3, rarity="rare", kantoReforged=true },
  { n=308, id="WX_308_CROCONAW_TEMPEST", base="CROCONAW", baseName="Croconaw", variant="TEMPEST", types={ "WATER", "ELECTRIC" }, weather="Storm", cohort=3, rarity="rare", kantoReforged=true },
  { n=309, id="WX_309_FERALIGATR_TEMPEST", base="FERALIGATR", baseName="Feraligatr", variant="TEMPEST", types={ "WATER", "ELECTRIC" }, weather="Storm", cohort=3, rarity="rare", kantoReforged=true },
  { n=310, id="WX_310_SENTRET_GALE", base="SENTRET", baseName="Sentret", variant="GALE", types={ "NORMAL", "FLYING" }, weather="Wind", cohort=3, rarity="rare", kantoReforged=true },
  { n=311, id="WX_311_FURRET_GALE", base="FURRET", baseName="Furret", variant="GALE", types={ "NORMAL", "FLYING" }, weather="Wind", cohort=3, rarity="rare", kantoReforged=true },
  { n=312, id="WX_312_HOOTHOOT_GALE", base="HOOTHOOT", baseName="Hoothoot", variant="GALE", types={ "NORMAL", "FLYING" }, weather="Wind", cohort=3, rarity="rare", kantoReforged=true },
  { n=313, id="WX_313_NOCTOWL_GALE", base="NOCTOWL", baseName="Noctowl", variant="GALE", types={ "NORMAL", "FLYING" }, weather="Wind", cohort=3, rarity="rare", kantoReforged=true },
  { n=314, id="WX_314_LEDYBA_DEW", base="LEDYBA", baseName="Ledyba", variant="DEW", types={ "BUG", "WATER" }, weather="Rain", cohort=3, rarity="rare", kantoReforged=true },
  { n=315, id="WX_315_LEDIAN_DEW", base="LEDIAN", baseName="Ledian", variant="DEW", types={ "BUG", "WATER" }, weather="Rain", cohort=3, rarity="rare", kantoReforged=true },
  { n=316, id="WX_316_SPINARAK_DEW", base="SPINARAK", baseName="Spinarak", variant="DEW", types={ "BUG", "WATER" }, weather="Rain", cohort=3, rarity="rare", kantoReforged=true },
  { n=317, id="WX_317_ARIADOS_DEW", base="ARIADOS", baseName="Ariados", variant="DEW", types={ "BUG", "WATER" }, weather="Rain", cohort=3, rarity="rare", kantoReforged=true },
  { n=318, id="WX_318_CROBAT_CAUSTIC", base="CROBAT", baseName="Crobat", variant="CAUSTIC", types={ "POISON", "WATER" }, weather="Acid Rain", cohort=3, rarity="rare", kantoReforged=true },
  { n=319, id="WX_319_CHINCHOU_TEMPEST", base="CHINCHOU", baseName="Chinchou", variant="TEMPEST", types={ "WATER", "ELECTRIC" }, weather="Storm", cohort=3, rarity="rare", kantoReforged=true },
  { n=320, id="WX_320_LANTURN_TEMPEST", base="LANTURN", baseName="Lanturn", variant="TEMPEST", types={ "WATER", "ELECTRIC" }, weather="Storm", cohort=3, rarity="rare", kantoReforged=true },
  { n=321, id="WX_321_PICHU_STATIC", base="PICHU", baseName="Pichu", variant="STATIC", types={ "ELECTRIC", "STEEL" }, weather="Thunderstorm", cohort=3, rarity="rare", kantoReforged=true },
  { n=322, id="WX_322_CLEFFA_GALE", base="CLEFFA", baseName="Cleffa", variant="GALE", types={ "NORMAL", "FLYING" }, weather="Wind", cohort=3, rarity="rare", kantoReforged=true },
  { n=323, id="WX_323_IGGLYBUFF_GALE", base="IGGLYBUFF", baseName="Igglybuff", variant="GALE", types={ "NORMAL", "FLYING" }, weather="Wind", cohort=3, rarity="rare", kantoReforged=true },
  { n=324, id="WX_324_TOGEPI_GALE", base="TOGEPI", baseName="Togepi", variant="GALE", types={ "NORMAL", "FLYING" }, weather="Wind", cohort=3, rarity="rare", kantoReforged=true },
  { n=325, id="WX_325_TOGETIC_GALE", base="TOGETIC", baseName="Togetic", variant="GALE", types={ "NORMAL", "FLYING" }, weather="Wind", cohort=3, rarity="rare", kantoReforged=true },
  { n=326, id="WX_326_NATU_DREAMFOG", base="NATU", baseName="Natu", variant="DREAMFOG", types={ "PSYCHIC_TYPE", "GHOST" }, weather="Moonlit Fog", cohort=3, rarity="rare", kantoReforged=true },
  { n=327, id="WX_327_XATU_DREAMFOG", base="XATU", baseName="Xatu", variant="DREAMFOG", types={ "PSYCHIC_TYPE", "GHOST" }, weather="Moonlit Fog", cohort=3, rarity="rare", kantoReforged=true },
  { n=328, id="WX_328_MAREEP_STATIC", base="MAREEP", baseName="Mareep", variant="STATIC", types={ "ELECTRIC", "STEEL" }, weather="Thunderstorm", cohort=3, rarity="rare", kantoReforged=true },
  { n=329, id="WX_329_FLAAFFY_STATIC", base="FLAAFFY", baseName="Flaaffy", variant="STATIC", types={ "ELECTRIC", "STEEL" }, weather="Thunderstorm", cohort=3, rarity="rare", kantoReforged=true },
  { n=330, id="WX_330_AMPHAROS_STATIC", base="AMPHAROS", baseName="Ampharos", variant="STATIC", types={ "ELECTRIC", "STEEL" }, weather="Thunderstorm", cohort=3, rarity="rare", kantoReforged=true },
  { n=331, id="WX_331_BELLOSSOM_BLOOM", base="BELLOSSOM", baseName="Bellossom", variant="BLOOM", types={ "GRASS", "FAIRY" }, weather="Spring Rain", cohort=3, rarity="rare", kantoReforged=true },
  { n=332, id="WX_332_MARILL_TEMPEST", base="MARILL", baseName="Marill", variant="TEMPEST", types={ "WATER", "ELECTRIC" }, weather="Storm", cohort=3, rarity="rare", kantoReforged=true },
  { n=333, id="WX_333_AZUMARILL_TEMPEST", base="AZUMARILL", baseName="Azumarill", variant="TEMPEST", types={ "WATER", "ELECTRIC" }, weather="Storm", cohort=3, rarity="rare", kantoReforged=true },
  { n=334, id="WX_334_SUDOWOODO_DUNE", base="SUDOWOODO", baseName="Sudowoodo", variant="DUNE", types={ "ROCK", "GROUND" }, weather="Sandstorm", cohort=3, rarity="rare", kantoReforged=true },
  { n=335, id="WX_335_POLITOED_TEMPEST", base="POLITOED", baseName="Politoed", variant="TEMPEST", types={ "WATER", "ELECTRIC" }, weather="Storm", cohort=3, rarity="rare", kantoReforged=true },
  { n=336, id="WX_336_HOPPIP_BLOOM", base="HOPPIP", baseName="Hoppip", variant="BLOOM", types={ "GRASS", "FAIRY" }, weather="Spring Rain", cohort=3, rarity="rare", kantoReforged=true },
  { n=337, id="WX_337_SKIPLOOM_BLOOM", base="SKIPLOOM", baseName="Skiploom", variant="BLOOM", types={ "GRASS", "FAIRY" }, weather="Spring Rain", cohort=3, rarity="rare", kantoReforged=true },
  { n=338, id="WX_338_JUMPLUFF_BLOOM", base="JUMPLUFF", baseName="Jumpluff", variant="BLOOM", types={ "GRASS", "FAIRY" }, weather="Spring Rain", cohort=3, rarity="rare", kantoReforged=true },
  { n=339, id="WX_339_AIPOM_GALE", base="AIPOM", baseName="Aipom", variant="GALE", types={ "NORMAL", "FLYING" }, weather="Wind", cohort=3, rarity="rare", kantoReforged=true },
  { n=340, id="WX_340_SUNKERN_BLOOM", base="SUNKERN", baseName="Sunkern", variant="BLOOM", types={ "GRASS", "FAIRY" }, weather="Spring Rain", cohort=3, rarity="rare", kantoReforged=true },
  { n=341, id="WX_341_SUNFLORA_BLOOM", base="SUNFLORA", baseName="Sunflora", variant="BLOOM", types={ "GRASS", "FAIRY" }, weather="Spring Rain", cohort=3, rarity="rare", kantoReforged=true },
  { n=342, id="WX_342_YANMA_DEW", base="YANMA", baseName="Yanma", variant="DEW", types={ "BUG", "WATER" }, weather="Rain", cohort=3, rarity="rare", kantoReforged=true },
  { n=343, id="WX_343_WOOPER_TEMPEST", base="WOOPER", baseName="Wooper", variant="TEMPEST", types={ "WATER", "ELECTRIC" }, weather="Storm", cohort=3, rarity="rare", kantoReforged=true },
  { n=344, id="WX_344_QUAGSIRE_TEMPEST", base="QUAGSIRE", baseName="Quagsire", variant="TEMPEST", types={ "WATER", "ELECTRIC" }, weather="Storm", cohort=3, rarity="rare", kantoReforged=true },
  { n=345, id="WX_345_ESPEON_DREAMFOG", base="ESPEON", baseName="Espeon", variant="DREAMFOG", types={ "PSYCHIC_TYPE", "GHOST" }, weather="Moonlit Fog", cohort=3, rarity="rare", kantoReforged=true },
  { n=346, id="WX_346_UMBREON_NIGHTFOG", base="UMBREON", baseName="Umbreon", variant="NIGHTFOG", types={ "DARK", "GHOST" }, weather="Moonlit Fog", cohort=3, rarity="rare", kantoReforged=true },
  { n=347, id="WX_347_MURKROW_NIGHTFOG", base="MURKROW", baseName="Murkrow", variant="NIGHTFOG", types={ "DARK", "GHOST" }, weather="Moonlit Fog", cohort=3, rarity="rare", kantoReforged=true },
  { n=348, id="WX_348_SLOWKING_TEMPEST", base="SLOWKING", baseName="Slowking", variant="TEMPEST", types={ "WATER", "ELECTRIC" }, weather="Storm", cohort=3, rarity="rare", kantoReforged=true },
  { n=349, id="WX_349_MISDREAVUS_MOONVEIL", base="MISDREAVUS", baseName="Misdreavus", variant="MOONVEIL", types={ "GHOST", "FAIRY" }, weather="Moonlit Fog", cohort=3, rarity="rare", kantoReforged=true },
  { n=350, id="WX_350_UNOWN_DREAMFOG", base="UNOWN", baseName="Unown", variant="DREAMFOG", types={ "PSYCHIC_TYPE", "GHOST" }, weather="Moonlit Fog", cohort=3, rarity="rare", kantoReforged=true },
  { n=351, id="WX_351_WOBBUFFET_DREAMFOG", base="WOBBUFFET", baseName="Wobbuffet", variant="DREAMFOG", types={ "PSYCHIC_TYPE", "GHOST" }, weather="Moonlit Fog", cohort=3, rarity="rare", kantoReforged=true },
  { n=352, id="WX_352_GIRAFARIG_GALE", base="GIRAFARIG", baseName="Girafarig", variant="GALE", types={ "NORMAL", "FLYING" }, weather="Wind", cohort=3, rarity="rare", kantoReforged=true },
  { n=353, id="WX_353_PINECO_DEW", base="PINECO", baseName="Pineco", variant="DEW", types={ "BUG", "WATER" }, weather="Rain", cohort=3, rarity="rare", kantoReforged=true },
  { n=354, id="WX_354_FORRETRESS_DEW", base="FORRETRESS", baseName="Forretress", variant="DEW", types={ "BUG", "WATER" }, weather="Rain", cohort=3, rarity="rare", kantoReforged=true },
  { n=355, id="WX_355_DUNSPARCE_GALE", base="DUNSPARCE", baseName="Dunsparce", variant="GALE", types={ "NORMAL", "FLYING" }, weather="Wind", cohort=3, rarity="rare", kantoReforged=true },
  { n=356, id="WX_356_GLIGAR_DUNE", base="GLIGAR", baseName="Gligar", variant="DUNE", types={ "GROUND", "ROCK" }, weather="Sandstorm", cohort=3, rarity="rare", kantoReforged=true },
  { n=357, id="WX_357_STEELIX_RIME", base="STEELIX", baseName="Steelix", variant="RIME", types={ "STEEL", "ICE" }, weather="Hail", cohort=3, rarity="veryRare", kantoReforged=true },
  { n=358, id="WX_358_SNUBBULL_GALE", base="SNUBBULL", baseName="Snubbull", variant="GALE", types={ "NORMAL", "FLYING" }, weather="Wind", cohort=3, rarity="rare", kantoReforged=true },
  { n=359, id="WX_359_GRANBULL_GALE", base="GRANBULL", baseName="Granbull", variant="GALE", types={ "NORMAL", "FLYING" }, weather="Wind", cohort=3, rarity="rare", kantoReforged=true },
  { n=360, id="WX_360_QWILFISH_TEMPEST", base="QWILFISH", baseName="Qwilfish", variant="TEMPEST", types={ "WATER", "ELECTRIC" }, weather="Storm", cohort=3, rarity="rare", kantoReforged=true },
  { n=361, id="WX_361_SCIZOR_DEW", base="SCIZOR", baseName="Scizor", variant="DEW", types={ "BUG", "WATER" }, weather="Rain", cohort=3, rarity="veryRare", kantoReforged=true },
  { n=362, id="WX_362_SHUCKLE_DEW", base="SHUCKLE", baseName="Shuckle", variant="DEW", types={ "BUG", "WATER" }, weather="Rain", cohort=3, rarity="rare", kantoReforged=true },
  { n=363, id="WX_363_HERACROSS_DEW", base="HERACROSS", baseName="Heracross", variant="DEW", types={ "BUG", "WATER" }, weather="Rain", cohort=3, rarity="rare", kantoReforged=true },
  { n=364, id="WX_364_SNEASEL_NIGHTFOG", base="SNEASEL", baseName="Sneasel", variant="NIGHTFOG", types={ "DARK", "GHOST" }, weather="Moonlit Fog", cohort=3, rarity="rare", kantoReforged=true },
  { n=365, id="WX_365_TEDDIURSA_GALE", base="TEDDIURSA", baseName="Teddiursa", variant="GALE", types={ "NORMAL", "FLYING" }, weather="Wind", cohort=3, rarity="rare", kantoReforged=true },
  { n=366, id="WX_366_URSARING_GALE", base="URSARING", baseName="Ursaring", variant="GALE", types={ "NORMAL", "FLYING" }, weather="Wind", cohort=3, rarity="rare", kantoReforged=true },
  { n=367, id="WX_367_SLUGMA_CINDER", base="SLUGMA", baseName="Slugma", variant="CINDER", types={ "FIRE", "GHOST" }, weather="Ashfall", cohort=3, rarity="rare", kantoReforged=true },
  { n=368, id="WX_368_MAGCARGO_CINDER", base="MAGCARGO", baseName="Magcargo", variant="CINDER", types={ "FIRE", "GHOST" }, weather="Ashfall", cohort=3, rarity="rare", kantoReforged=true },
  { n=369, id="WX_369_SWINUB_WHITEOUT", base="SWINUB", baseName="Swinub", variant="WHITEOUT", types={ "ICE", "GHOST" }, weather="Blizzard", cohort=3, rarity="rare", kantoReforged=true },
  { n=370, id="WX_370_PILOSWINE_WHITEOUT", base="PILOSWINE", baseName="Piloswine", variant="WHITEOUT", types={ "ICE", "GHOST" }, weather="Blizzard", cohort=3, rarity="rare", kantoReforged=true },
  { n=371, id="WX_371_CORSOLA_TEMPEST", base="CORSOLA", baseName="Corsola", variant="TEMPEST", types={ "WATER", "ELECTRIC" }, weather="Storm", cohort=3, rarity="rare", kantoReforged=true },
  { n=372, id="WX_372_REMORAID_TEMPEST", base="REMORAID", baseName="Remoraid", variant="TEMPEST", types={ "WATER", "ELECTRIC" }, weather="Storm", cohort=3, rarity="rare", kantoReforged=true },
  { n=373, id="WX_373_OCTILLERY_TEMPEST", base="OCTILLERY", baseName="Octillery", variant="TEMPEST", types={ "WATER", "ELECTRIC" }, weather="Storm", cohort=3, rarity="rare", kantoReforged=true },
  { n=374, id="WX_374_DELIBIRD_WHITEOUT", base="DELIBIRD", baseName="Delibird", variant="WHITEOUT", types={ "ICE", "GHOST" }, weather="Blizzard", cohort=3, rarity="rare", kantoReforged=true },
  { n=375, id="WX_375_MANTINE_TEMPEST", base="MANTINE", baseName="Mantine", variant="TEMPEST", types={ "WATER", "ELECTRIC" }, weather="Storm", cohort=3, rarity="veryRare", kantoReforged=true },
  { n=376, id="WX_376_SKARMORY_RIME", base="SKARMORY", baseName="Skarmory", variant="RIME", types={ "STEEL", "ICE" }, weather="Hail", cohort=3, rarity="veryRare", kantoReforged=true },
  { n=377, id="WX_377_HOUNDOUR_NIGHTFOG", base="HOUNDOUR", baseName="Houndour", variant="NIGHTFOG", types={ "DARK", "GHOST" }, weather="Moonlit Fog", cohort=3, rarity="rare", kantoReforged=true },
  { n=378, id="WX_378_HOUNDOOM_NIGHTFOG", base="HOUNDOOM", baseName="Houndoom", variant="NIGHTFOG", types={ "DARK", "GHOST" }, weather="Moonlit Fog", cohort=3, rarity="rare", kantoReforged=true },
  { n=379, id="WX_379_KINGDRA_TEMPEST", base="KINGDRA", baseName="Kingdra", variant="TEMPEST", types={ "WATER", "ELECTRIC" }, weather="Storm", cohort=3, rarity="rare", kantoReforged=true },
  { n=380, id="WX_380_PHANPY_DUNE", base="PHANPY", baseName="Phanpy", variant="DUNE", types={ "GROUND", "ROCK" }, weather="Sandstorm", cohort=3, rarity="rare", kantoReforged=true },
  { n=381, id="WX_381_DONPHAN_DUNE", base="DONPHAN", baseName="Donphan", variant="DUNE", types={ "GROUND", "ROCK" }, weather="Sandstorm", cohort=3, rarity="rare", kantoReforged=true },
  { n=382, id="WX_382_PORYGON2_GALE", base="PORYGON2", baseName="Porygon2", variant="GALE", types={ "NORMAL", "FLYING" }, weather="Wind", cohort=3, rarity="rare", kantoReforged=true },
  { n=383, id="WX_383_STANTLER_GALE", base="STANTLER", baseName="Stantler", variant="GALE", types={ "NORMAL", "FLYING" }, weather="Wind", cohort=3, rarity="rare", kantoReforged=true },
  { n=384, id="WX_384_SMEARGLE_GALE", base="SMEARGLE", baseName="Smeargle", variant="GALE", types={ "NORMAL", "FLYING" }, weather="Wind", cohort=3, rarity="rare", kantoReforged=true },
  { n=385, id="WX_385_TYROGUE_TEMPEST", base="TYROGUE", baseName="Tyrogue", variant="TEMPEST", types={ "FIGHTING", "FLYING" }, weather="Wind", cohort=3, rarity="rare", kantoReforged=true },
  { n=386, id="WX_386_HITMONTOP_TEMPEST", base="HITMONTOP", baseName="Hitmontop", variant="TEMPEST", types={ "FIGHTING", "FLYING" }, weather="Wind", cohort=3, rarity="rare", kantoReforged=true },
  { n=387, id="WX_387_SMOOCHUM_WHITEOUT", base="SMOOCHUM", baseName="Smoochum", variant="WHITEOUT", types={ "ICE", "GHOST" }, weather="Blizzard", cohort=3, rarity="rare", kantoReforged=true },
  { n=388, id="WX_388_ELEKID_STATIC", base="ELEKID", baseName="Elekid", variant="STATIC", types={ "ELECTRIC", "STEEL" }, weather="Thunderstorm", cohort=3, rarity="rare", kantoReforged=true },
  { n=389, id="WX_389_MAGBY_CINDER", base="MAGBY", baseName="Magby", variant="CINDER", types={ "FIRE", "GHOST" }, weather="Ashfall", cohort=3, rarity="rare", kantoReforged=true },
  { n=390, id="WX_390_MILTANK_GALE", base="MILTANK", baseName="Miltank", variant="GALE", types={ "NORMAL", "FLYING" }, weather="Wind", cohort=3, rarity="rare", kantoReforged=true },
  { n=391, id="WX_391_BLISSEY_GALE", base="BLISSEY", baseName="Blissey", variant="GALE", types={ "NORMAL", "FLYING" }, weather="Wind", cohort=3, rarity="rare", kantoReforged=true },
  { n=392, id="WX_392_RAIKOU_STATIC", base="RAIKOU", baseName="Raikou", variant="STATIC", types={ "ELECTRIC", "STEEL" }, weather="Thunderstorm", cohort=3, rarity="legendary", kantoReforged=true },
  { n=393, id="WX_393_ENTEI_CINDER", base="ENTEI", baseName="Entei", variant="CINDER", types={ "FIRE", "GHOST" }, weather="Ashfall", cohort=3, rarity="legendary", kantoReforged=true },
  { n=394, id="WX_394_SUICUNE_TEMPEST", base="SUICUNE", baseName="Suicune", variant="TEMPEST", types={ "WATER", "ELECTRIC" }, weather="Storm", cohort=3, rarity="legendary", kantoReforged=true },
  { n=395, id="WX_395_LARVITAR_DUNE", base="LARVITAR", baseName="Larvitar", variant="DUNE", types={ "ROCK", "GROUND" }, weather="Sandstorm", cohort=3, rarity="rare", kantoReforged=true },
  { n=396, id="WX_396_PUPITAR_DUNE", base="PUPITAR", baseName="Pupitar", variant="DUNE", types={ "ROCK", "GROUND" }, weather="Sandstorm", cohort=3, rarity="rare", kantoReforged=true },
  { n=397, id="WX_397_TYRANITAR_DUNE", base="TYRANITAR", baseName="Tyranitar", variant="DUNE", types={ "ROCK", "GROUND" }, weather="Sandstorm", cohort=3, rarity="rare", kantoReforged=true },
  { n=398, id="WX_398_LUGIA_DREAMFOG", base="LUGIA", baseName="Lugia", variant="DREAMFOG", types={ "PSYCHIC_TYPE", "GHOST" }, weather="Moonlit Fog", cohort=3, rarity="legendary", kantoReforged=true },
  { n=399, id="WX_399_HO_OH_CINDER", base="HO_OH", baseName="Ho Oh", variant="CINDER", types={ "FIRE", "GHOST" }, weather="Ashfall", cohort=3, rarity="legendary", kantoReforged=true },
  { n=400, id="WX_400_CELEBI_DREAMFOG", base="CELEBI", baseName="Celebi", variant="DREAMFOG", types={ "PSYCHIC_TYPE", "GHOST" }, weather="Moonlit Fog", cohort=3, rarity="legendary", kantoReforged=true },
  { n=401, id="WX_401_TREECKO_BLOOM", base="TREECKO", baseName="Treecko", variant="BLOOM", types={ "GRASS", "FAIRY" }, weather="Spring Rain", cohort=3, rarity="rare", kantoReforged=true },
  { n=402, id="WX_402_GROVYLE_BLOOM", base="GROVYLE", baseName="Grovyle", variant="BLOOM", types={ "GRASS", "FAIRY" }, weather="Spring Rain", cohort=3, rarity="rare", kantoReforged=true },
  { n=403, id="WX_403_SCEPTILE_BLOOM", base="SCEPTILE", baseName="Sceptile", variant="BLOOM", types={ "GRASS", "FAIRY" }, weather="Spring Rain", cohort=3, rarity="rare", kantoReforged=true },
  { n=404, id="WX_404_TORCHIC_CINDER", base="TORCHIC", baseName="Torchic", variant="CINDER", types={ "FIRE", "GHOST" }, weather="Ashfall", cohort=3, rarity="rare", kantoReforged=true },
  { n=405, id="WX_405_COMBUSKEN_CINDER", base="COMBUSKEN", baseName="Combusken", variant="CINDER", types={ "FIRE", "GHOST" }, weather="Ashfall", cohort=3, rarity="rare", kantoReforged=true },
  { n=406, id="WX_406_BLAZIKEN_CINDER", base="BLAZIKEN", baseName="Blaziken", variant="CINDER", types={ "FIRE", "GHOST" }, weather="Ashfall", cohort=3, rarity="rare", kantoReforged=true },
  { n=407, id="WX_407_MUDKIP_TEMPEST", base="MUDKIP", baseName="Mudkip", variant="TEMPEST", types={ "WATER", "ELECTRIC" }, weather="Storm", cohort=3, rarity="rare", kantoReforged=true },
  { n=408, id="WX_408_MARSHTOMP_TEMPEST", base="MARSHTOMP", baseName="Marshtomp", variant="TEMPEST", types={ "WATER", "ELECTRIC" }, weather="Storm", cohort=3, rarity="rare", kantoReforged=true },
  { n=409, id="WX_409_SWAMPERT_TEMPEST", base="SWAMPERT", baseName="Swampert", variant="TEMPEST", types={ "WATER", "ELECTRIC" }, weather="Storm", cohort=3, rarity="rare", kantoReforged=true },
  { n=410, id="WX_410_POOCHYENA_NIGHTFOG", base="POOCHYENA", baseName="Poochyena", variant="NIGHTFOG", types={ "DARK", "GHOST" }, weather="Moonlit Fog", cohort=3, rarity="rare", kantoReforged=true },
  { n=411, id="WX_411_MIGHTYENA_NIGHTFOG", base="MIGHTYENA", baseName="Mightyena", variant="NIGHTFOG", types={ "DARK", "GHOST" }, weather="Moonlit Fog", cohort=3, rarity="rare", kantoReforged=true },
  { n=412, id="WX_412_ZIGZAGOON_GALE", base="ZIGZAGOON", baseName="Zigzagoon", variant="GALE", types={ "NORMAL", "FLYING" }, weather="Wind", cohort=3, rarity="rare", kantoReforged=true },
  { n=413, id="WX_413_LINOONE_GALE", base="LINOONE", baseName="Linoone", variant="GALE", types={ "NORMAL", "FLYING" }, weather="Wind", cohort=3, rarity="rare", kantoReforged=true },
  { n=414, id="WX_414_WURMPLE_DEW", base="WURMPLE", baseName="Wurmple", variant="DEW", types={ "BUG", "WATER" }, weather="Rain", cohort=3, rarity="rare", kantoReforged=true },
  { n=415, id="WX_415_SILCOON_DEW", base="SILCOON", baseName="Silcoon", variant="DEW", types={ "BUG", "WATER" }, weather="Rain", cohort=3, rarity="rare", kantoReforged=true },
  { n=416, id="WX_416_BEAUTIFLY_DEW", base="BEAUTIFLY", baseName="Beautifly", variant="DEW", types={ "BUG", "WATER" }, weather="Rain", cohort=3, rarity="rare", kantoReforged=true },
  { n=417, id="WX_417_CASCOON_DEW", base="CASCOON", baseName="Cascoon", variant="DEW", types={ "BUG", "WATER" }, weather="Rain", cohort=3, rarity="rare", kantoReforged=true },
  { n=418, id="WX_418_DUSTOX_DEW", base="DUSTOX", baseName="Dustox", variant="DEW", types={ "BUG", "WATER" }, weather="Rain", cohort=3, rarity="rare", kantoReforged=true },
  { n=419, id="WX_419_LOTAD_TEMPEST", base="LOTAD", baseName="Lotad", variant="TEMPEST", types={ "WATER", "ELECTRIC" }, weather="Storm", cohort=3, rarity="rare", kantoReforged=true },
  { n=420, id="WX_420_LOMBRE_TEMPEST", base="LOMBRE", baseName="Lombre", variant="TEMPEST", types={ "WATER", "ELECTRIC" }, weather="Storm", cohort=3, rarity="rare", kantoReforged=true },
  { n=421, id="WX_421_LUDICOLO_TEMPEST", base="LUDICOLO", baseName="Ludicolo", variant="TEMPEST", types={ "WATER", "ELECTRIC" }, weather="Storm", cohort=3, rarity="rare", kantoReforged=true },
  { n=422, id="WX_422_SEEDOT_BLOOM", base="SEEDOT", baseName="Seedot", variant="BLOOM", types={ "GRASS", "FAIRY" }, weather="Spring Rain", cohort=3, rarity="rare", kantoReforged=true },
  { n=423, id="WX_423_NUZLEAF_BLOOM", base="NUZLEAF", baseName="Nuzleaf", variant="BLOOM", types={ "GRASS", "FAIRY" }, weather="Spring Rain", cohort=3, rarity="rare", kantoReforged=true },
  { n=424, id="WX_424_SHIFTRY_BLOOM", base="SHIFTRY", baseName="Shiftry", variant="BLOOM", types={ "GRASS", "FAIRY" }, weather="Spring Rain", cohort=3, rarity="rare", kantoReforged=true },
  { n=425, id="WX_425_TAILLOW_GALE", base="TAILLOW", baseName="Taillow", variant="GALE", types={ "NORMAL", "FLYING" }, weather="Wind", cohort=3, rarity="rare", kantoReforged=true },
  { n=426, id="WX_426_SWELLOW_GALE", base="SWELLOW", baseName="Swellow", variant="GALE", types={ "NORMAL", "FLYING" }, weather="Wind", cohort=3, rarity="rare", kantoReforged=true },
  { n=427, id="WX_427_WINGULL_TEMPEST", base="WINGULL", baseName="Wingull", variant="TEMPEST", types={ "WATER", "ELECTRIC" }, weather="Storm", cohort=3, rarity="rare", kantoReforged=true },
  { n=428, id="WX_428_PELIPPER_TEMPEST", base="PELIPPER", baseName="Pelipper", variant="TEMPEST", types={ "WATER", "ELECTRIC" }, weather="Storm", cohort=3, rarity="rare", kantoReforged=true },
  { n=429, id="WX_429_RALTS_DREAMFOG", base="RALTS", baseName="Ralts", variant="DREAMFOG", types={ "PSYCHIC_TYPE", "GHOST" }, weather="Moonlit Fog", cohort=3, rarity="rare", kantoReforged=true },
  { n=430, id="WX_430_KIRLIA_DREAMFOG", base="KIRLIA", baseName="Kirlia", variant="DREAMFOG", types={ "PSYCHIC_TYPE", "GHOST" }, weather="Moonlit Fog", cohort=3, rarity="rare", kantoReforged=true },
  { n=431, id="WX_431_GARDEVOIR_DREAMFOG", base="GARDEVOIR", baseName="Gardevoir", variant="DREAMFOG", types={ "PSYCHIC_TYPE", "GHOST" }, weather="Moonlit Fog", cohort=3, rarity="rare", kantoReforged=true },
  { n=432, id="WX_432_SURSKIT_DEW", base="SURSKIT", baseName="Surskit", variant="DEW", types={ "BUG", "WATER" }, weather="Rain", cohort=3, rarity="rare", kantoReforged=true },
  { n=433, id="WX_433_MASQUERAIN_DEW", base="MASQUERAIN", baseName="Masquerain", variant="DEW", types={ "BUG", "WATER" }, weather="Rain", cohort=3, rarity="rare", kantoReforged=true },
  { n=434, id="WX_434_SHROOMISH_BLOOM", base="SHROOMISH", baseName="Shroomish", variant="BLOOM", types={ "GRASS", "FAIRY" }, weather="Spring Rain", cohort=3, rarity="rare", kantoReforged=true },
  { n=435, id="WX_435_BRELOOM_BLOOM", base="BRELOOM", baseName="Breloom", variant="BLOOM", types={ "GRASS", "FAIRY" }, weather="Spring Rain", cohort=3, rarity="rare", kantoReforged=true },
  { n=436, id="WX_436_SLAKOTH_GALE", base="SLAKOTH", baseName="Slakoth", variant="GALE", types={ "NORMAL", "FLYING" }, weather="Wind", cohort=3, rarity="rare", kantoReforged=true },
  { n=437, id="WX_437_VIGOROTH_GALE", base="VIGOROTH", baseName="Vigoroth", variant="GALE", types={ "NORMAL", "FLYING" }, weather="Wind", cohort=3, rarity="rare", kantoReforged=true },
  { n=438, id="WX_438_SLAKING_GALE", base="SLAKING", baseName="Slaking", variant="GALE", types={ "NORMAL", "FLYING" }, weather="Wind", cohort=3, rarity="rare", kantoReforged=true },
  { n=439, id="WX_439_NINCADA_DEW", base="NINCADA", baseName="Nincada", variant="DEW", types={ "BUG", "WATER" }, weather="Rain", cohort=3, rarity="rare", kantoReforged=true },
  { n=440, id="WX_440_NINJASK_DEW", base="NINJASK", baseName="Ninjask", variant="DEW", types={ "BUG", "WATER" }, weather="Rain", cohort=3, rarity="rare", kantoReforged=true },
  { n=441, id="WX_441_SHEDINJA_DEW", base="SHEDINJA", baseName="Shedinja", variant="DEW", types={ "BUG", "WATER" }, weather="Rain", cohort=3, rarity="rare", kantoReforged=true },
  { n=442, id="WX_442_WHISMUR_GALE", base="WHISMUR", baseName="Whismur", variant="GALE", types={ "NORMAL", "FLYING" }, weather="Wind", cohort=3, rarity="rare", kantoReforged=true },
  { n=443, id="WX_443_LOUDRED_GALE", base="LOUDRED", baseName="Loudred", variant="GALE", types={ "NORMAL", "FLYING" }, weather="Wind", cohort=3, rarity="rare", kantoReforged=true },
  { n=444, id="WX_444_EXPLOUD_GALE", base="EXPLOUD", baseName="Exploud", variant="GALE", types={ "NORMAL", "FLYING" }, weather="Wind", cohort=3, rarity="rare", kantoReforged=true },
  { n=445, id="WX_445_MAKUHITA_TEMPEST", base="MAKUHITA", baseName="Makuhita", variant="TEMPEST", types={ "FIGHTING", "FLYING" }, weather="Wind", cohort=3, rarity="rare", kantoReforged=true },
  { n=446, id="WX_446_HARIYAMA_TEMPEST", base="HARIYAMA", baseName="Hariyama", variant="TEMPEST", types={ "FIGHTING", "FLYING" }, weather="Wind", cohort=3, rarity="rare", kantoReforged=true },
  { n=447, id="WX_447_AZURILL_GALE", base="AZURILL", baseName="Azurill", variant="GALE", types={ "NORMAL", "FLYING" }, weather="Wind", cohort=3, rarity="rare", kantoReforged=true },
  { n=448, id="WX_448_NOSEPASS_DUNE", base="NOSEPASS", baseName="Nosepass", variant="DUNE", types={ "ROCK", "GROUND" }, weather="Sandstorm", cohort=3, rarity="rare", kantoReforged=true },
  { n=449, id="WX_449_SKITTY_GALE", base="SKITTY", baseName="Skitty", variant="GALE", types={ "NORMAL", "FLYING" }, weather="Wind", cohort=3, rarity="rare", kantoReforged=true },
  { n=450, id="WX_450_DELCATTY_GALE", base="DELCATTY", baseName="Delcatty", variant="GALE", types={ "NORMAL", "FLYING" }, weather="Wind", cohort=3, rarity="rare", kantoReforged=true },
  { n=451, id="WX_451_SABLEYE_NIGHTFOG", base="SABLEYE", baseName="Sableye", variant="NIGHTFOG", types={ "DARK", "GHOST" }, weather="Moonlit Fog", cohort=3, rarity="rare", kantoReforged=true },
  { n=452, id="WX_452_MAWILE_RIME", base="MAWILE", baseName="Mawile", variant="RIME", types={ "STEEL", "ICE" }, weather="Hail", cohort=3, rarity="rare", kantoReforged=true },
  { n=453, id="WX_453_ARON_RIME", base="ARON", baseName="Aron", variant="RIME", types={ "STEEL", "ICE" }, weather="Hail", cohort=3, rarity="rare", kantoReforged=true },
  { n=454, id="WX_454_LAIRON_RIME", base="LAIRON", baseName="Lairon", variant="RIME", types={ "STEEL", "ICE" }, weather="Hail", cohort=3, rarity="rare", kantoReforged=true },
  { n=455, id="WX_455_AGGRON_RIME", base="AGGRON", baseName="Aggron", variant="RIME", types={ "STEEL", "ICE" }, weather="Hail", cohort=3, rarity="rare", kantoReforged=true },
  { n=456, id="WX_456_MEDITITE_TEMPEST", base="MEDITITE", baseName="Meditite", variant="TEMPEST", types={ "FIGHTING", "FLYING" }, weather="Wind", cohort=3, rarity="rare", kantoReforged=true },
  { n=457, id="WX_457_MEDICHAM_TEMPEST", base="MEDICHAM", baseName="Medicham", variant="TEMPEST", types={ "FIGHTING", "FLYING" }, weather="Wind", cohort=3, rarity="rare", kantoReforged=true },
  { n=458, id="WX_458_ELECTRIKE_STATIC", base="ELECTRIKE", baseName="Electrike", variant="STATIC", types={ "ELECTRIC", "STEEL" }, weather="Thunderstorm", cohort=3, rarity="rare", kantoReforged=true },
  { n=459, id="WX_459_MANECTRIC_STATIC", base="MANECTRIC", baseName="Manectric", variant="STATIC", types={ "ELECTRIC", "STEEL" }, weather="Thunderstorm", cohort=3, rarity="rare", kantoReforged=true },
  { n=460, id="WX_460_PLUSLE_STATIC", base="PLUSLE", baseName="Plusle", variant="STATIC", types={ "ELECTRIC", "STEEL" }, weather="Thunderstorm", cohort=3, rarity="rare", kantoReforged=true },
  { n=461, id="WX_461_MINUN_STATIC", base="MINUN", baseName="Minun", variant="STATIC", types={ "ELECTRIC", "STEEL" }, weather="Thunderstorm", cohort=3, rarity="rare", kantoReforged=true },
  { n=462, id="WX_462_VOLBEAT_DEW", base="VOLBEAT", baseName="Volbeat", variant="DEW", types={ "BUG", "WATER" }, weather="Rain", cohort=3, rarity="rare", kantoReforged=true },
  { n=463, id="WX_463_ILLUMISE_DEW", base="ILLUMISE", baseName="Illumise", variant="DEW", types={ "BUG", "WATER" }, weather="Rain", cohort=3, rarity="rare", kantoReforged=true },
  { n=464, id="WX_464_ROSELIA_BLOOM", base="ROSELIA", baseName="Roselia", variant="BLOOM", types={ "GRASS", "FAIRY" }, weather="Spring Rain", cohort=3, rarity="rare", kantoReforged=true },
  { n=465, id="WX_465_GULPIN_CAUSTIC", base="GULPIN", baseName="Gulpin", variant="CAUSTIC", types={ "POISON", "WATER" }, weather="Acid Rain", cohort=3, rarity="rare", kantoReforged=true },
  { n=466, id="WX_466_SWALOT_CAUSTIC", base="SWALOT", baseName="Swalot", variant="CAUSTIC", types={ "POISON", "WATER" }, weather="Acid Rain", cohort=3, rarity="rare", kantoReforged=true },
  { n=467, id="WX_467_CARVANHA_TEMPEST", base="CARVANHA", baseName="Carvanha", variant="TEMPEST", types={ "WATER", "ELECTRIC" }, weather="Storm", cohort=3, rarity="rare", kantoReforged=true },
  { n=468, id="WX_468_SHARPEDO_TEMPEST", base="SHARPEDO", baseName="Sharpedo", variant="TEMPEST", types={ "WATER", "ELECTRIC" }, weather="Storm", cohort=3, rarity="rare", kantoReforged=true },
  { n=469, id="WX_469_WAILMER_TEMPEST", base="WAILMER", baseName="Wailmer", variant="TEMPEST", types={ "WATER", "ELECTRIC" }, weather="Storm", cohort=3, rarity="rare", kantoReforged=true },
  { n=470, id="WX_470_WAILORD_TEMPEST", base="WAILORD", baseName="Wailord", variant="TEMPEST", types={ "WATER", "ELECTRIC" }, weather="Storm", cohort=3, rarity="rare", kantoReforged=true },
  { n=471, id="WX_471_NUMEL_CINDER", base="NUMEL", baseName="Numel", variant="CINDER", types={ "FIRE", "GHOST" }, weather="Ashfall", cohort=3, rarity="rare", kantoReforged=true },
  { n=472, id="WX_472_CAMERUPT_CINDER", base="CAMERUPT", baseName="Camerupt", variant="CINDER", types={ "FIRE", "GHOST" }, weather="Ashfall", cohort=3, rarity="rare", kantoReforged=true },
  { n=473, id="WX_473_TORKOAL_CINDER", base="TORKOAL", baseName="Torkoal", variant="CINDER", types={ "FIRE", "GHOST" }, weather="Ashfall", cohort=3, rarity="rare", kantoReforged=true },
  { n=474, id="WX_474_SPOINK_DREAMFOG", base="SPOINK", baseName="Spoink", variant="DREAMFOG", types={ "PSYCHIC_TYPE", "GHOST" }, weather="Moonlit Fog", cohort=3, rarity="rare", kantoReforged=true },
  { n=475, id="WX_475_GRUMPIG_DREAMFOG", base="GRUMPIG", baseName="Grumpig", variant="DREAMFOG", types={ "PSYCHIC_TYPE", "GHOST" }, weather="Moonlit Fog", cohort=3, rarity="rare", kantoReforged=true },
  { n=476, id="WX_476_SPINDA_GALE", base="SPINDA", baseName="Spinda", variant="GALE", types={ "NORMAL", "FLYING" }, weather="Wind", cohort=3, rarity="rare", kantoReforged=true },
  { n=477, id="WX_477_TRAPINCH_DUNE", base="TRAPINCH", baseName="Trapinch", variant="DUNE", types={ "GROUND", "ROCK" }, weather="Sandstorm", cohort=3, rarity="rare", kantoReforged=true },
  { n=478, id="WX_478_VIBRAVA_DUNE", base="VIBRAVA", baseName="Vibrava", variant="DUNE", types={ "GROUND", "ROCK" }, weather="Sandstorm", cohort=3, rarity="rare", kantoReforged=true },
  { n=479, id="WX_479_FLYGON_DUNE", base="FLYGON", baseName="Flygon", variant="DUNE", types={ "GROUND", "ROCK" }, weather="Sandstorm", cohort=3, rarity="rare", kantoReforged=true },
  { n=480, id="WX_480_CACNEA_BLOOM", base="CACNEA", baseName="Cacnea", variant="BLOOM", types={ "GRASS", "FAIRY" }, weather="Spring Rain", cohort=3, rarity="rare", kantoReforged=true },
  { n=481, id="WX_481_CACTURNE_BLOOM", base="CACTURNE", baseName="Cacturne", variant="BLOOM", types={ "GRASS", "FAIRY" }, weather="Spring Rain", cohort=3, rarity="rare", kantoReforged=true },
  { n=482, id="WX_482_SWABLU_GALE", base="SWABLU", baseName="Swablu", variant="GALE", types={ "NORMAL", "FLYING" }, weather="Wind", cohort=3, rarity="rare", kantoReforged=true },
  { n=483, id="WX_483_ALTARIA_TEMPEST", base="ALTARIA", baseName="Altaria", variant="TEMPEST", types={ "DRAGON", "WATER" }, weather="Typhoon", cohort=3, rarity="rare", kantoReforged=true },
  { n=484, id="WX_484_ZANGOOSE_GALE", base="ZANGOOSE", baseName="Zangoose", variant="GALE", types={ "NORMAL", "FLYING" }, weather="Wind", cohort=3, rarity="rare", kantoReforged=true },
  { n=485, id="WX_485_SEVIPER_CAUSTIC", base="SEVIPER", baseName="Seviper", variant="CAUSTIC", types={ "POISON", "WATER" }, weather="Acid Rain", cohort=3, rarity="rare", kantoReforged=true },
  { n=486, id="WX_486_LUNATONE_DUNE", base="LUNATONE", baseName="Lunatone", variant="DUNE", types={ "ROCK", "GROUND" }, weather="Sandstorm", cohort=3, rarity="rare", kantoReforged=true },
  { n=487, id="WX_487_SOLROCK_DUNE", base="SOLROCK", baseName="Solrock", variant="DUNE", types={ "ROCK", "GROUND" }, weather="Sandstorm", cohort=3, rarity="rare", kantoReforged=true },
  { n=488, id="WX_488_BARBOACH_TEMPEST", base="BARBOACH", baseName="Barboach", variant="TEMPEST", types={ "WATER", "ELECTRIC" }, weather="Storm", cohort=3, rarity="rare", kantoReforged=true },
  { n=489, id="WX_489_WHISCASH_TEMPEST", base="WHISCASH", baseName="Whiscash", variant="TEMPEST", types={ "WATER", "ELECTRIC" }, weather="Storm", cohort=3, rarity="rare", kantoReforged=true },
  { n=490, id="WX_490_CORPHISH_TEMPEST", base="CORPHISH", baseName="Corphish", variant="TEMPEST", types={ "WATER", "ELECTRIC" }, weather="Storm", cohort=3, rarity="rare", kantoReforged=true },
  { n=491, id="WX_491_CRAWDAUNT_TEMPEST", base="CRAWDAUNT", baseName="Crawdaunt", variant="TEMPEST", types={ "WATER", "ELECTRIC" }, weather="Storm", cohort=3, rarity="rare", kantoReforged=true },
  { n=492, id="WX_492_BALTOY_DUNE", base="BALTOY", baseName="Baltoy", variant="DUNE", types={ "GROUND", "ROCK" }, weather="Sandstorm", cohort=3, rarity="rare", kantoReforged=true },
  { n=493, id="WX_493_CLAYDOL_DUNE", base="CLAYDOL", baseName="Claydol", variant="DUNE", types={ "GROUND", "ROCK" }, weather="Sandstorm", cohort=3, rarity="rare", kantoReforged=true },
  { n=494, id="WX_494_LILEEP_DUNE", base="LILEEP", baseName="Lileep", variant="DUNE", types={ "ROCK", "GROUND" }, weather="Sandstorm", cohort=3, rarity="rare", kantoReforged=true },
  { n=495, id="WX_495_CRADILY_DUNE", base="CRADILY", baseName="Cradily", variant="DUNE", types={ "ROCK", "GROUND" }, weather="Sandstorm", cohort=3, rarity="rare", kantoReforged=true },
  { n=496, id="WX_496_ANORITH_DUNE", base="ANORITH", baseName="Anorith", variant="DUNE", types={ "ROCK", "GROUND" }, weather="Sandstorm", cohort=3, rarity="rare", kantoReforged=true },
  { n=497, id="WX_497_ARMALDO_DUNE", base="ARMALDO", baseName="Armaldo", variant="DUNE", types={ "ROCK", "GROUND" }, weather="Sandstorm", cohort=3, rarity="rare", kantoReforged=true },
  { n=498, id="WX_498_FEEBAS_TEMPEST", base="FEEBAS", baseName="Feebas", variant="TEMPEST", types={ "WATER", "ELECTRIC" }, weather="Storm", cohort=3, rarity="rare", kantoReforged=true },
  { n=499, id="WX_499_MILOTIC_TEMPEST", base="MILOTIC", baseName="Milotic", variant="TEMPEST", types={ "WATER", "ELECTRIC" }, weather="Storm", cohort=3, rarity="rare", kantoReforged=true },
  { n=500, id="WX_500_CASTFORM_GALE", base="CASTFORM", baseName="Castform", variant="GALE", types={ "NORMAL", "FLYING" }, weather="Wind", cohort=3, rarity="rare", kantoReforged=true },
  { n=501, id="WX_501_KECLEON_GALE", base="KECLEON", baseName="Kecleon", variant="GALE", types={ "NORMAL", "FLYING" }, weather="Wind", cohort=3, rarity="rare", kantoReforged=true },
  { n=502, id="WX_502_SHUPPET_MOONVEIL", base="SHUPPET", baseName="Shuppet", variant="MOONVEIL", types={ "GHOST", "FAIRY" }, weather="Moonlit Fog", cohort=3, rarity="rare", kantoReforged=true },
  { n=503, id="WX_503_BANETTE_MOONVEIL", base="BANETTE", baseName="Banette", variant="MOONVEIL", types={ "GHOST", "FAIRY" }, weather="Moonlit Fog", cohort=3, rarity="rare", kantoReforged=true },
  { n=504, id="WX_504_DUSKULL_MOONVEIL", base="DUSKULL", baseName="Duskull", variant="MOONVEIL", types={ "GHOST", "FAIRY" }, weather="Moonlit Fog", cohort=3, rarity="rare", kantoReforged=true },
  { n=505, id="WX_505_DUSCLOPS_MOONVEIL", base="DUSCLOPS", baseName="Dusclops", variant="MOONVEIL", types={ "GHOST", "FAIRY" }, weather="Moonlit Fog", cohort=3, rarity="rare", kantoReforged=true },
  { n=506, id="WX_506_TROPIUS_BLOOM", base="TROPIUS", baseName="Tropius", variant="BLOOM", types={ "GRASS", "FAIRY" }, weather="Spring Rain", cohort=3, rarity="rare", kantoReforged=true },
  { n=507, id="WX_507_CHIMECHO_DREAMFOG", base="CHIMECHO", baseName="Chimecho", variant="DREAMFOG", types={ "PSYCHIC_TYPE", "GHOST" }, weather="Moonlit Fog", cohort=3, rarity="rare", kantoReforged=true },
  { n=508, id="WX_508_ABSOL_NIGHTFOG", base="ABSOL", baseName="Absol", variant="NIGHTFOG", types={ "DARK", "GHOST" }, weather="Moonlit Fog", cohort=3, rarity="rare", kantoReforged=true },
  { n=509, id="WX_509_WYNAUT_DREAMFOG", base="WYNAUT", baseName="Wynaut", variant="DREAMFOG", types={ "PSYCHIC_TYPE", "GHOST" }, weather="Moonlit Fog", cohort=3, rarity="rare", kantoReforged=true },
  { n=510, id="WX_510_SNORUNT_WHITEOUT", base="SNORUNT", baseName="Snorunt", variant="WHITEOUT", types={ "ICE", "GHOST" }, weather="Blizzard", cohort=3, rarity="rare", kantoReforged=true },
  { n=511, id="WX_511_GLALIE_WHITEOUT", base="GLALIE", baseName="Glalie", variant="WHITEOUT", types={ "ICE", "GHOST" }, weather="Blizzard", cohort=3, rarity="rare", kantoReforged=true },
  { n=512, id="WX_512_SPHEAL_WHITEOUT", base="SPHEAL", baseName="Spheal", variant="WHITEOUT", types={ "ICE", "GHOST" }, weather="Blizzard", cohort=3, rarity="rare", kantoReforged=true },
  { n=513, id="WX_513_SEALEO_WHITEOUT", base="SEALEO", baseName="Sealeo", variant="WHITEOUT", types={ "ICE", "GHOST" }, weather="Blizzard", cohort=3, rarity="rare", kantoReforged=true },
  { n=514, id="WX_514_WALREIN_WHITEOUT", base="WALREIN", baseName="Walrein", variant="WHITEOUT", types={ "ICE", "GHOST" }, weather="Blizzard", cohort=3, rarity="rare", kantoReforged=true },
  { n=515, id="WX_515_CLAMPERL_TEMPEST", base="CLAMPERL", baseName="Clamperl", variant="TEMPEST", types={ "WATER", "ELECTRIC" }, weather="Storm", cohort=3, rarity="rare", kantoReforged=true },
  { n=516, id="WX_516_HUNTAIL_TEMPEST", base="HUNTAIL", baseName="Huntail", variant="TEMPEST", types={ "WATER", "ELECTRIC" }, weather="Storm", cohort=3, rarity="rare", kantoReforged=true },
  { n=517, id="WX_517_GOREBYSS_TEMPEST", base="GOREBYSS", baseName="Gorebyss", variant="TEMPEST", types={ "WATER", "ELECTRIC" }, weather="Storm", cohort=3, rarity="rare", kantoReforged=true },
  { n=518, id="WX_518_RELICANTH_TEMPEST", base="RELICANTH", baseName="Relicanth", variant="TEMPEST", types={ "WATER", "ELECTRIC" }, weather="Storm", cohort=3, rarity="veryRare", kantoReforged=true },
  { n=519, id="WX_519_LUVDISC_TEMPEST", base="LUVDISC", baseName="Luvdisc", variant="TEMPEST", types={ "WATER", "ELECTRIC" }, weather="Storm", cohort=3, rarity="rare", kantoReforged=true },
  { n=520, id="WX_520_BAGON_TEMPEST", base="BAGON", baseName="Bagon", variant="TEMPEST", types={ "DRAGON", "WATER" }, weather="Typhoon", cohort=3, rarity="rare", kantoReforged=true },
  { n=521, id="WX_521_SHELGON_TEMPEST", base="SHELGON", baseName="Shelgon", variant="TEMPEST", types={ "DRAGON", "WATER" }, weather="Typhoon", cohort=3, rarity="rare", kantoReforged=true },
  { n=522, id="WX_522_SALAMENCE_TEMPEST", base="SALAMENCE", baseName="Salamence", variant="TEMPEST", types={ "DRAGON", "WATER" }, weather="Typhoon", cohort=3, rarity="rare", kantoReforged=true },
  { n=523, id="WX_523_BELDUM_RIME", base="BELDUM", baseName="Beldum", variant="RIME", types={ "STEEL", "ICE" }, weather="Hail", cohort=3, rarity="legendary", kantoReforged=true },
  { n=524, id="WX_524_METANG_RIME", base="METANG", baseName="Metang", variant="RIME", types={ "STEEL", "ICE" }, weather="Hail", cohort=3, rarity="legendary", kantoReforged=true },
  { n=525, id="WX_525_METAGROSS_RIME", base="METAGROSS", baseName="Metagross", variant="RIME", types={ "STEEL", "ICE" }, weather="Hail", cohort=3, rarity="legendary", kantoReforged=true },
  { n=526, id="WX_526_REGIROCK_DUNE", base="REGIROCK", baseName="Regirock", variant="DUNE", types={ "ROCK", "GROUND" }, weather="Sandstorm", cohort=3, rarity="legendary", kantoReforged=true },
  { n=527, id="WX_527_REGICE_WHITEOUT", base="REGICE", baseName="Regice", variant="WHITEOUT", types={ "ICE", "GHOST" }, weather="Blizzard", cohort=3, rarity="legendary", kantoReforged=true },
  { n=528, id="WX_528_REGISTEEL_RIME", base="REGISTEEL", baseName="Registeel", variant="RIME", types={ "STEEL", "ICE" }, weather="Hail", cohort=3, rarity="legendary", kantoReforged=true },
  { n=529, id="WX_529_LATIAS_TEMPEST", base="LATIAS", baseName="Latias", variant="TEMPEST", types={ "DRAGON", "WATER" }, weather="Typhoon", cohort=3, rarity="legendary", kantoReforged=true },
  { n=530, id="WX_530_LATIOS_TEMPEST", base="LATIOS", baseName="Latios", variant="TEMPEST", types={ "DRAGON", "WATER" }, weather="Typhoon", cohort=3, rarity="legendary", kantoReforged=true },
  { n=531, id="WX_531_KYOGRE_TEMPEST", base="KYOGRE", baseName="Kyogre", variant="TEMPEST", types={ "WATER", "ELECTRIC" }, weather="Storm", cohort=3, rarity="legendary", kantoReforged=true },
  { n=532, id="WX_532_GROUDON_DUNE", base="GROUDON", baseName="Groudon", variant="DUNE", types={ "GROUND", "ROCK" }, weather="Sandstorm", cohort=3, rarity="legendary", kantoReforged=true },
  { n=533, id="WX_533_RAYQUAZA_TEMPEST", base="RAYQUAZA", baseName="Rayquaza", variant="TEMPEST", types={ "DRAGON", "WATER" }, weather="Typhoon", cohort=3, rarity="legendary", kantoReforged=true },
  { n=534, id="WX_534_JIRACHI_RIME", base="JIRACHI", baseName="Jirachi", variant="RIME", types={ "STEEL", "ICE" }, weather="Hail", cohort=3, rarity="legendary", kantoReforged=true },
  { n=535, id="WX_535_DEOXYS_NORMAL_DREAMFOG", base="DEOXYS_NORMAL", baseName="Deoxys Normal", variant="DREAMFOG", types={ "PSYCHIC_TYPE", "GHOST" }, weather="Moonlit Fog", cohort=3, rarity="legendary", kantoReforged=true },
  { n=536, id="WX_536_CHIKORITA_AUTUMN", base="CHIKORITA", baseName="Chikorita", variant="AUTUMN", types={ "GRASS", "GHOST" }, weather="Autumn Rain", cohort=4, rarity="rare", kantoReforged=true },
  { n=537, id="WX_537_BAYLEEF_AUTUMN", base="BAYLEEF", baseName="Bayleef", variant="AUTUMN", types={ "GRASS", "GHOST" }, weather="Autumn Rain", cohort=4, rarity="rare", kantoReforged=true },
  { n=538, id="WX_538_MEGANIUM_AUTUMN", base="MEGANIUM", baseName="Meganium", variant="AUTUMN", types={ "GRASS", "GHOST" }, weather="Autumn Rain", cohort=4, rarity="rare", kantoReforged=true },
  { n=539, id="WX_539_CYNDAQUIL_SOLAR", base="CYNDAQUIL", baseName="Cyndaquil", variant="SOLAR", types={ "FIRE", "DRAGON" }, weather="Heatwave", cohort=4, rarity="rare", kantoReforged=true },
  { n=540, id="WX_540_QUILAVA_SOLAR", base="QUILAVA", baseName="Quilava", variant="SOLAR", types={ "FIRE", "DRAGON" }, weather="Heatwave", cohort=4, rarity="rare", kantoReforged=true },
  { n=541, id="WX_541_TYPHLOSION_SOLAR", base="TYPHLOSION", baseName="Typhlosion", variant="SOLAR", types={ "FIRE", "DRAGON" }, weather="Heatwave", cohort=4, rarity="rare", kantoReforged=true },
  { n=542, id="WX_542_TOTODILE_RIME", base="TOTODILE", baseName="Totodile", variant="RIME", types={ "WATER", "ICE" }, weather="Hail", cohort=4, rarity="rare", kantoReforged=true },
  { n=543, id="WX_543_CROCONAW_RIME", base="CROCONAW", baseName="Croconaw", variant="RIME", types={ "WATER", "ICE" }, weather="Hail", cohort=4, rarity="rare", kantoReforged=true },
  { n=544, id="WX_544_FERALIGATR_RIME", base="FERALIGATR", baseName="Feraligatr", variant="RIME", types={ "WATER", "ICE" }, weather="Hail", cohort=4, rarity="rare", kantoReforged=true },
  { n=545, id="WX_545_SENTRET_UMBRAL", base="SENTRET", baseName="Sentret", variant="UMBRAL", types={ "NORMAL", "DARK" }, weather="Eclipse", cohort=4, rarity="rare", kantoReforged=true },
  { n=546, id="WX_546_FURRET_UMBRAL", base="FURRET", baseName="Furret", variant="UMBRAL", types={ "NORMAL", "DARK" }, weather="Eclipse", cohort=4, rarity="rare", kantoReforged=true },
  { n=547, id="WX_547_HOOTHOOT_UMBRAL", base="HOOTHOOT", baseName="Hoothoot", variant="UMBRAL", types={ "NORMAL", "DARK" }, weather="Eclipse", cohort=4, rarity="rare", kantoReforged=true },
  { n=548, id="WX_548_NOCTOWL_UMBRAL", base="NOCTOWL", baseName="Noctowl", variant="UMBRAL", types={ "NORMAL", "DARK" }, weather="Eclipse", cohort=4, rarity="rare", kantoReforged=true },
  { n=549, id="WX_549_LEDYBA_ASHEN", base="LEDYBA", baseName="Ledyba", variant="ASHEN", types={ "BUG", "FIRE" }, weather="Ashfall", cohort=4, rarity="rare", kantoReforged=true },
  { n=550, id="WX_550_LEDIAN_ASHEN", base="LEDIAN", baseName="Ledian", variant="ASHEN", types={ "BUG", "FIRE" }, weather="Ashfall", cohort=4, rarity="rare", kantoReforged=true },
  { n=551, id="WX_551_SPINARAK_ASHEN", base="SPINARAK", baseName="Spinarak", variant="ASHEN", types={ "BUG", "FIRE" }, weather="Ashfall", cohort=4, rarity="rare", kantoReforged=true },
  { n=552, id="WX_552_ARIADOS_ASHEN", base="ARIADOS", baseName="Ariados", variant="ASHEN", types={ "BUG", "FIRE" }, weather="Ashfall", cohort=4, rarity="rare", kantoReforged=true },
  { n=553, id="WX_553_CROBAT_SMOG", base="CROBAT", baseName="Crobat", variant="SMOG", types={ "POISON", "DARK" }, weather="Smog", cohort=4, rarity="rare", kantoReforged=true },
  { n=554, id="WX_554_CHINCHOU_RIME", base="CHINCHOU", baseName="Chinchou", variant="RIME", types={ "WATER", "ICE" }, weather="Hail", cohort=4, rarity="rare", kantoReforged=true },
  { n=555, id="WX_555_LANTURN_RIME", base="LANTURN", baseName="Lanturn", variant="RIME", types={ "WATER", "ICE" }, weather="Hail", cohort=4, rarity="rare", kantoReforged=true },
  { n=556, id="WX_556_PICHU_AURORA", base="PICHU", baseName="Pichu", variant="AURORA", types={ "ELECTRIC", "FAIRY" }, weather="Aurora", cohort=4, rarity="rare", kantoReforged=true },
  { n=557, id="WX_557_CLEFFA_UMBRAL", base="CLEFFA", baseName="Cleffa", variant="UMBRAL", types={ "NORMAL", "DARK" }, weather="Eclipse", cohort=4, rarity="rare", kantoReforged=true },
  { n=558, id="WX_558_IGGLYBUFF_UMBRAL", base="IGGLYBUFF", baseName="Igglybuff", variant="UMBRAL", types={ "NORMAL", "DARK" }, weather="Eclipse", cohort=4, rarity="rare", kantoReforged=true },
  { n=559, id="WX_559_TOGEPI_UMBRAL", base="TOGEPI", baseName="Togepi", variant="UMBRAL", types={ "NORMAL", "DARK" }, weather="Eclipse", cohort=4, rarity="rare", kantoReforged=true },
  { n=560, id="WX_560_TOGETIC_UMBRAL", base="TOGETIC", baseName="Togetic", variant="UMBRAL", types={ "NORMAL", "DARK" }, weather="Eclipse", cohort=4, rarity="rare", kantoReforged=true },
  { n=561, id="WX_561_NATU_ECLIPSE", base="NATU", baseName="Natu", variant="ECLIPSE", types={ "PSYCHIC_TYPE", "DARK" }, weather="Eclipse", cohort=4, rarity="rare", kantoReforged=true },
  { n=562, id="WX_562_XATU_ECLIPSE", base="XATU", baseName="Xatu", variant="ECLIPSE", types={ "PSYCHIC_TYPE", "DARK" }, weather="Eclipse", cohort=4, rarity="rare", kantoReforged=true },
  { n=563, id="WX_563_MAREEP_AURORA", base="MAREEP", baseName="Mareep", variant="AURORA", types={ "ELECTRIC", "FAIRY" }, weather="Aurora", cohort=4, rarity="rare", kantoReforged=true },
  { n=564, id="WX_564_FLAAFFY_AURORA", base="FLAAFFY", baseName="Flaaffy", variant="AURORA", types={ "ELECTRIC", "FAIRY" }, weather="Aurora", cohort=4, rarity="rare", kantoReforged=true },
  { n=565, id="WX_565_AMPHAROS_AURORA", base="AMPHAROS", baseName="Ampharos", variant="AURORA", types={ "ELECTRIC", "FAIRY" }, weather="Aurora", cohort=4, rarity="rare", kantoReforged=true },
  { n=566, id="WX_566_BELLOSSOM_AUTUMN", base="BELLOSSOM", baseName="Bellossom", variant="AUTUMN", types={ "GRASS", "GHOST" }, weather="Autumn Rain", cohort=4, rarity="rare", kantoReforged=true },
  { n=567, id="WX_567_MARILL_RIME", base="MARILL", baseName="Marill", variant="RIME", types={ "WATER", "ICE" }, weather="Hail", cohort=4, rarity="rare", kantoReforged=true },
  { n=568, id="WX_568_AZUMARILL_RIME", base="AZUMARILL", baseName="Azumarill", variant="RIME", types={ "WATER", "ICE" }, weather="Hail", cohort=4, rarity="rare", kantoReforged=true },
  { n=569, id="WX_569_SUDOWOODO_FOSSILFROST", base="SUDOWOODO", baseName="Sudowoodo", variant="FOSSILFROST", types={ "ROCK", "ICE" }, weather="Hail", cohort=4, rarity="rare", kantoReforged=true },
  { n=570, id="WX_570_POLITOED_RIME", base="POLITOED", baseName="Politoed", variant="RIME", types={ "WATER", "ICE" }, weather="Hail", cohort=4, rarity="rare", kantoReforged=true },
  { n=571, id="WX_571_HOPPIP_AUTUMN", base="HOPPIP", baseName="Hoppip", variant="AUTUMN", types={ "GRASS", "GHOST" }, weather="Autumn Rain", cohort=4, rarity="rare", kantoReforged=true },
  { n=572, id="WX_572_SKIPLOOM_AUTUMN", base="SKIPLOOM", baseName="Skiploom", variant="AUTUMN", types={ "GRASS", "GHOST" }, weather="Autumn Rain", cohort=4, rarity="rare", kantoReforged=true },
  { n=573, id="WX_573_JUMPLUFF_AUTUMN", base="JUMPLUFF", baseName="Jumpluff", variant="AUTUMN", types={ "GRASS", "GHOST" }, weather="Autumn Rain", cohort=4, rarity="rare", kantoReforged=true },
  { n=574, id="WX_574_AIPOM_UMBRAL", base="AIPOM", baseName="Aipom", variant="UMBRAL", types={ "NORMAL", "DARK" }, weather="Eclipse", cohort=4, rarity="rare", kantoReforged=true },
  { n=575, id="WX_575_SUNKERN_AUTUMN", base="SUNKERN", baseName="Sunkern", variant="AUTUMN", types={ "GRASS", "GHOST" }, weather="Autumn Rain", cohort=4, rarity="rare", kantoReforged=true },
  { n=576, id="WX_576_SUNFLORA_AUTUMN", base="SUNFLORA", baseName="Sunflora", variant="AUTUMN", types={ "GRASS", "GHOST" }, weather="Autumn Rain", cohort=4, rarity="rare", kantoReforged=true },
  { n=577, id="WX_577_YANMA_ASHEN", base="YANMA", baseName="Yanma", variant="ASHEN", types={ "BUG", "FIRE" }, weather="Ashfall", cohort=4, rarity="rare", kantoReforged=true },
  { n=578, id="WX_578_WOOPER_RIME", base="WOOPER", baseName="Wooper", variant="RIME", types={ "WATER", "ICE" }, weather="Hail", cohort=4, rarity="rare", kantoReforged=true },
  { n=579, id="WX_579_QUAGSIRE_RIME", base="QUAGSIRE", baseName="Quagsire", variant="RIME", types={ "WATER", "ICE" }, weather="Hail", cohort=4, rarity="rare", kantoReforged=true },
  { n=580, id="WX_580_ESPEON_ECLIPSE", base="ESPEON", baseName="Espeon", variant="ECLIPSE", types={ "PSYCHIC_TYPE", "DARK" }, weather="Eclipse", cohort=4, rarity="rare", kantoReforged=true },
  { n=581, id="WX_581_UMBREON_DUST", base="UMBREON", baseName="Umbreon", variant="DUST", types={ "DARK", "GROUND" }, weather="Dust Storm", cohort=4, rarity="rare", kantoReforged=true },
  { n=582, id="WX_582_MURKROW_DUST", base="MURKROW", baseName="Murkrow", variant="DUST", types={ "DARK", "GROUND" }, weather="Dust Storm", cohort=4, rarity="rare", kantoReforged=true },
  { n=583, id="WX_583_SLOWKING_RIME", base="SLOWKING", baseName="Slowking", variant="RIME", types={ "WATER", "ICE" }, weather="Hail", cohort=4, rarity="rare", kantoReforged=true },
  { n=584, id="WX_584_MISDREAVUS_STATIC", base="MISDREAVUS", baseName="Misdreavus", variant="STATIC", types={ "GHOST", "ELECTRIC" }, weather="Static Storm", cohort=4, rarity="rare", kantoReforged=true },
  { n=585, id="WX_585_UNOWN_ECLIPSE", base="UNOWN", baseName="Unown", variant="ECLIPSE", types={ "PSYCHIC_TYPE", "DARK" }, weather="Eclipse", cohort=4, rarity="rare", kantoReforged=true },
  { n=586, id="WX_586_WOBBUFFET_ECLIPSE", base="WOBBUFFET", baseName="Wobbuffet", variant="ECLIPSE", types={ "PSYCHIC_TYPE", "DARK" }, weather="Eclipse", cohort=4, rarity="rare", kantoReforged=true },
  { n=587, id="WX_587_GIRAFARIG_UMBRAL", base="GIRAFARIG", baseName="Girafarig", variant="UMBRAL", types={ "NORMAL", "DARK" }, weather="Eclipse", cohort=4, rarity="rare", kantoReforged=true },
  { n=588, id="WX_588_PINECO_ASHEN", base="PINECO", baseName="Pineco", variant="ASHEN", types={ "BUG", "FIRE" }, weather="Ashfall", cohort=4, rarity="rare", kantoReforged=true },
  { n=589, id="WX_589_FORRETRESS_ASHEN", base="FORRETRESS", baseName="Forretress", variant="ASHEN", types={ "BUG", "FIRE" }, weather="Ashfall", cohort=4, rarity="rare", kantoReforged=true },
  { n=590, id="WX_590_DUNSPARCE_UMBRAL", base="DUNSPARCE", baseName="Dunsparce", variant="UMBRAL", types={ "NORMAL", "DARK" }, weather="Eclipse", cohort=4, rarity="rare", kantoReforged=true },
  { n=591, id="WX_591_GLIGAR_MIRE", base="GLIGAR", baseName="Gligar", variant="MIRE", types={ "GROUND", "WATER" }, weather="Heavy Rain", cohort=4, rarity="rare", kantoReforged=true },
  { n=592, id="WX_592_STEELIX_STATIC", base="STEELIX", baseName="Steelix", variant="STATIC", types={ "STEEL", "ELECTRIC" }, weather="Thunderstorm", cohort=4, rarity="veryRare", kantoReforged=true },
  { n=593, id="WX_593_SNUBBULL_UMBRAL", base="SNUBBULL", baseName="Snubbull", variant="UMBRAL", types={ "NORMAL", "DARK" }, weather="Eclipse", cohort=4, rarity="rare", kantoReforged=true },
  { n=594, id="WX_594_GRANBULL_UMBRAL", base="GRANBULL", baseName="Granbull", variant="UMBRAL", types={ "NORMAL", "DARK" }, weather="Eclipse", cohort=4, rarity="rare", kantoReforged=true },
  { n=595, id="WX_595_QWILFISH_RIME", base="QWILFISH", baseName="Qwilfish", variant="RIME", types={ "WATER", "ICE" }, weather="Hail", cohort=4, rarity="rare", kantoReforged=true },
  { n=596, id="WX_596_SCIZOR_ASHEN", base="SCIZOR", baseName="Scizor", variant="ASHEN", types={ "BUG", "FIRE" }, weather="Ashfall", cohort=4, rarity="veryRare", kantoReforged=true },
  { n=597, id="WX_597_SHUCKLE_ASHEN", base="SHUCKLE", baseName="Shuckle", variant="ASHEN", types={ "BUG", "FIRE" }, weather="Ashfall", cohort=4, rarity="rare", kantoReforged=true },
  { n=598, id="WX_598_HERACROSS_ASHEN", base="HERACROSS", baseName="Heracross", variant="ASHEN", types={ "BUG", "FIRE" }, weather="Ashfall", cohort=4, rarity="rare", kantoReforged=true },
  { n=599, id="WX_599_SNEASEL_DUST", base="SNEASEL", baseName="Sneasel", variant="DUST", types={ "DARK", "GROUND" }, weather="Dust Storm", cohort=4, rarity="rare", kantoReforged=true },
  { n=600, id="WX_600_TEDDIURSA_UMBRAL", base="TEDDIURSA", baseName="Teddiursa", variant="UMBRAL", types={ "NORMAL", "DARK" }, weather="Eclipse", cohort=4, rarity="rare", kantoReforged=true },
  { n=601, id="WX_601_URSARING_UMBRAL", base="URSARING", baseName="Ursaring", variant="UMBRAL", types={ "NORMAL", "DARK" }, weather="Eclipse", cohort=4, rarity="rare", kantoReforged=true },
  { n=602, id="WX_602_SLUGMA_SOLAR", base="SLUGMA", baseName="Slugma", variant="SOLAR", types={ "FIRE", "DRAGON" }, weather="Heatwave", cohort=4, rarity="rare", kantoReforged=true },
  { n=603, id="WX_603_MAGCARGO_SOLAR", base="MAGCARGO", baseName="Magcargo", variant="SOLAR", types={ "FIRE", "DRAGON" }, weather="Heatwave", cohort=4, rarity="rare", kantoReforged=true },
  { n=604, id="WX_604_SWINUB_AURORA", base="SWINUB", baseName="Swinub", variant="AURORA", types={ "ICE", "PSYCHIC_TYPE" }, weather="Aurora", cohort=4, rarity="rare", kantoReforged=true },
  { n=605, id="WX_605_PILOSWINE_AURORA", base="PILOSWINE", baseName="Piloswine", variant="AURORA", types={ "ICE", "PSYCHIC_TYPE" }, weather="Aurora", cohort=4, rarity="rare", kantoReforged=true },
  { n=606, id="WX_606_CORSOLA_RIME", base="CORSOLA", baseName="Corsola", variant="RIME", types={ "WATER", "ICE" }, weather="Hail", cohort=4, rarity="rare", kantoReforged=true },
  { n=607, id="WX_607_REMORAID_RIME", base="REMORAID", baseName="Remoraid", variant="RIME", types={ "WATER", "ICE" }, weather="Hail", cohort=4, rarity="rare", kantoReforged=true },
  { n=608, id="WX_608_OCTILLERY_RIME", base="OCTILLERY", baseName="Octillery", variant="RIME", types={ "WATER", "ICE" }, weather="Hail", cohort=4, rarity="rare", kantoReforged=true },
  { n=609, id="WX_609_DELIBIRD_AURORA", base="DELIBIRD", baseName="Delibird", variant="AURORA", types={ "ICE", "PSYCHIC_TYPE" }, weather="Aurora", cohort=4, rarity="rare", kantoReforged=true },
  { n=610, id="WX_610_MANTINE_RIME", base="MANTINE", baseName="Mantine", variant="RIME", types={ "WATER", "ICE" }, weather="Hail", cohort=4, rarity="veryRare", kantoReforged=true },
  { n=611, id="WX_611_SKARMORY_STATIC", base="SKARMORY", baseName="Skarmory", variant="STATIC", types={ "STEEL", "ELECTRIC" }, weather="Thunderstorm", cohort=4, rarity="veryRare", kantoReforged=true },
  { n=612, id="WX_612_HOUNDOUR_DUST", base="HOUNDOUR", baseName="Houndour", variant="DUST", types={ "DARK", "GROUND" }, weather="Dust Storm", cohort=4, rarity="rare", kantoReforged=true },
  { n=613, id="WX_613_HOUNDOOM_DUST", base="HOUNDOOM", baseName="Houndoom", variant="DUST", types={ "DARK", "GROUND" }, weather="Dust Storm", cohort=4, rarity="rare", kantoReforged=true },
  { n=614, id="WX_614_KINGDRA_RIME", base="KINGDRA", baseName="Kingdra", variant="RIME", types={ "WATER", "ICE" }, weather="Hail", cohort=4, rarity="rare", kantoReforged=true },
  { n=615, id="WX_615_PHANPY_MIRE", base="PHANPY", baseName="Phanpy", variant="MIRE", types={ "GROUND", "WATER" }, weather="Heavy Rain", cohort=4, rarity="rare", kantoReforged=true },
  { n=616, id="WX_616_DONPHAN_MIRE", base="DONPHAN", baseName="Donphan", variant="MIRE", types={ "GROUND", "WATER" }, weather="Heavy Rain", cohort=4, rarity="rare", kantoReforged=true },
  { n=617, id="WX_617_PORYGON2_UMBRAL", base="PORYGON2", baseName="Porygon2", variant="UMBRAL", types={ "NORMAL", "DARK" }, weather="Eclipse", cohort=4, rarity="rare", kantoReforged=true },
  { n=618, id="WX_618_STANTLER_UMBRAL", base="STANTLER", baseName="Stantler", variant="UMBRAL", types={ "NORMAL", "DARK" }, weather="Eclipse", cohort=4, rarity="rare", kantoReforged=true },
  { n=619, id="WX_619_SMEARGLE_UMBRAL", base="SMEARGLE", baseName="Smeargle", variant="UMBRAL", types={ "NORMAL", "DARK" }, weather="Eclipse", cohort=4, rarity="rare", kantoReforged=true },
  { n=620, id="WX_620_TYROGUE_IRON", base="TYROGUE", baseName="Tyrogue", variant="IRON", types={ "FIGHTING", "STEEL" }, weather="Dust Storm", cohort=4, rarity="rare", kantoReforged=true },
  { n=621, id="WX_621_HITMONTOP_IRON", base="HITMONTOP", baseName="Hitmontop", variant="IRON", types={ "FIGHTING", "STEEL" }, weather="Dust Storm", cohort=4, rarity="rare", kantoReforged=true },
  { n=622, id="WX_622_SMOOCHUM_AURORA", base="SMOOCHUM", baseName="Smoochum", variant="AURORA", types={ "ICE", "PSYCHIC_TYPE" }, weather="Aurora", cohort=4, rarity="rare", kantoReforged=true },
  { n=623, id="WX_623_ELEKID_AURORA", base="ELEKID", baseName="Elekid", variant="AURORA", types={ "ELECTRIC", "FAIRY" }, weather="Aurora", cohort=4, rarity="rare", kantoReforged=true },
  { n=624, id="WX_624_MAGBY_SOLAR", base="MAGBY", baseName="Magby", variant="SOLAR", types={ "FIRE", "DRAGON" }, weather="Heatwave", cohort=4, rarity="rare", kantoReforged=true },
  { n=625, id="WX_625_MILTANK_UMBRAL", base="MILTANK", baseName="Miltank", variant="UMBRAL", types={ "NORMAL", "DARK" }, weather="Eclipse", cohort=4, rarity="rare", kantoReforged=true },
  { n=626, id="WX_626_BLISSEY_UMBRAL", base="BLISSEY", baseName="Blissey", variant="UMBRAL", types={ "NORMAL", "DARK" }, weather="Eclipse", cohort=4, rarity="rare", kantoReforged=true },
  { n=627, id="WX_627_RAIKOU_AURORA", base="RAIKOU", baseName="Raikou", variant="AURORA", types={ "ELECTRIC", "FAIRY" }, weather="Aurora", cohort=4, rarity="legendary", kantoReforged=true },
  { n=628, id="WX_628_ENTEI_SOLAR", base="ENTEI", baseName="Entei", variant="SOLAR", types={ "FIRE", "DRAGON" }, weather="Heatwave", cohort=4, rarity="legendary", kantoReforged=true },
  { n=629, id="WX_629_SUICUNE_RIME", base="SUICUNE", baseName="Suicune", variant="RIME", types={ "WATER", "ICE" }, weather="Hail", cohort=4, rarity="legendary", kantoReforged=true },
  { n=630, id="WX_630_LARVITAR_FOSSILFROST", base="LARVITAR", baseName="Larvitar", variant="FOSSILFROST", types={ "ROCK", "ICE" }, weather="Hail", cohort=4, rarity="rare", kantoReforged=true },
  { n=631, id="WX_631_PUPITAR_FOSSILFROST", base="PUPITAR", baseName="Pupitar", variant="FOSSILFROST", types={ "ROCK", "ICE" }, weather="Hail", cohort=4, rarity="rare", kantoReforged=true },
  { n=632, id="WX_632_TYRANITAR_FOSSILFROST", base="TYRANITAR", baseName="Tyranitar", variant="FOSSILFROST", types={ "ROCK", "ICE" }, weather="Hail", cohort=4, rarity="rare", kantoReforged=true },
  { n=633, id="WX_633_LUGIA_ECLIPSE", base="LUGIA", baseName="Lugia", variant="ECLIPSE", types={ "PSYCHIC_TYPE", "DARK" }, weather="Eclipse", cohort=4, rarity="legendary", kantoReforged=true },
  { n=634, id="WX_634_HO_OH_SOLAR", base="HO_OH", baseName="Ho Oh", variant="SOLAR", types={ "FIRE", "DRAGON" }, weather="Heatwave", cohort=4, rarity="legendary", kantoReforged=true },
  { n=635, id="WX_635_CELEBI_ECLIPSE", base="CELEBI", baseName="Celebi", variant="ECLIPSE", types={ "PSYCHIC_TYPE", "DARK" }, weather="Eclipse", cohort=4, rarity="legendary", kantoReforged=true },
  { n=636, id="WX_636_TREECKO_AUTUMN", base="TREECKO", baseName="Treecko", variant="AUTUMN", types={ "GRASS", "GHOST" }, weather="Autumn Rain", cohort=4, rarity="rare", kantoReforged=true },
  { n=637, id="WX_637_GROVYLE_AUTUMN", base="GROVYLE", baseName="Grovyle", variant="AUTUMN", types={ "GRASS", "GHOST" }, weather="Autumn Rain", cohort=4, rarity="rare", kantoReforged=true },
  { n=638, id="WX_638_SCEPTILE_AUTUMN", base="SCEPTILE", baseName="Sceptile", variant="AUTUMN", types={ "GRASS", "GHOST" }, weather="Autumn Rain", cohort=4, rarity="rare", kantoReforged=true },
  { n=639, id="WX_639_TORCHIC_SOLAR", base="TORCHIC", baseName="Torchic", variant="SOLAR", types={ "FIRE", "DRAGON" }, weather="Heatwave", cohort=4, rarity="rare", kantoReforged=true },
  { n=640, id="WX_640_COMBUSKEN_SOLAR", base="COMBUSKEN", baseName="Combusken", variant="SOLAR", types={ "FIRE", "DRAGON" }, weather="Heatwave", cohort=4, rarity="rare", kantoReforged=true },
  { n=641, id="WX_641_BLAZIKEN_SOLAR", base="BLAZIKEN", baseName="Blaziken", variant="SOLAR", types={ "FIRE", "DRAGON" }, weather="Heatwave", cohort=4, rarity="rare", kantoReforged=true },
  { n=642, id="WX_642_MUDKIP_RIME", base="MUDKIP", baseName="Mudkip", variant="RIME", types={ "WATER", "ICE" }, weather="Hail", cohort=4, rarity="rare", kantoReforged=true },
  { n=643, id="WX_643_MARSHTOMP_RIME", base="MARSHTOMP", baseName="Marshtomp", variant="RIME", types={ "WATER", "ICE" }, weather="Hail", cohort=4, rarity="rare", kantoReforged=true },
  { n=644, id="WX_644_SWAMPERT_RIME", base="SWAMPERT", baseName="Swampert", variant="RIME", types={ "WATER", "ICE" }, weather="Hail", cohort=4, rarity="rare", kantoReforged=true },
  { n=645, id="WX_645_POOCHYENA_DUST", base="POOCHYENA", baseName="Poochyena", variant="DUST", types={ "DARK", "GROUND" }, weather="Dust Storm", cohort=4, rarity="rare", kantoReforged=true },
  { n=646, id="WX_646_MIGHTYENA_DUST", base="MIGHTYENA", baseName="Mightyena", variant="DUST", types={ "DARK", "GROUND" }, weather="Dust Storm", cohort=4, rarity="rare", kantoReforged=true },
  { n=647, id="WX_647_ZIGZAGOON_UMBRAL", base="ZIGZAGOON", baseName="Zigzagoon", variant="UMBRAL", types={ "NORMAL", "DARK" }, weather="Eclipse", cohort=4, rarity="rare", kantoReforged=true },
  { n=648, id="WX_648_LINOONE_UMBRAL", base="LINOONE", baseName="Linoone", variant="UMBRAL", types={ "NORMAL", "DARK" }, weather="Eclipse", cohort=4, rarity="rare", kantoReforged=true },
  { n=649, id="WX_649_WURMPLE_ASHEN", base="WURMPLE", baseName="Wurmple", variant="ASHEN", types={ "BUG", "FIRE" }, weather="Ashfall", cohort=4, rarity="rare", kantoReforged=true },
  { n=650, id="WX_650_SILCOON_ASHEN", base="SILCOON", baseName="Silcoon", variant="ASHEN", types={ "BUG", "FIRE" }, weather="Ashfall", cohort=4, rarity="rare", kantoReforged=true },
  { n=651, id="WX_651_BEAUTIFLY_ASHEN", base="BEAUTIFLY", baseName="Beautifly", variant="ASHEN", types={ "BUG", "FIRE" }, weather="Ashfall", cohort=4, rarity="rare", kantoReforged=true },
  { n=652, id="WX_652_CASCOON_ASHEN", base="CASCOON", baseName="Cascoon", variant="ASHEN", types={ "BUG", "FIRE" }, weather="Ashfall", cohort=4, rarity="rare", kantoReforged=true },
  { n=653, id="WX_653_DUSTOX_ASHEN", base="DUSTOX", baseName="Dustox", variant="ASHEN", types={ "BUG", "FIRE" }, weather="Ashfall", cohort=4, rarity="rare", kantoReforged=true },
  { n=654, id="WX_654_LOTAD_RIME", base="LOTAD", baseName="Lotad", variant="RIME", types={ "WATER", "ICE" }, weather="Hail", cohort=4, rarity="rare", kantoReforged=true },
  { n=655, id="WX_655_LOMBRE_RIME", base="LOMBRE", baseName="Lombre", variant="RIME", types={ "WATER", "ICE" }, weather="Hail", cohort=4, rarity="rare", kantoReforged=true },
  { n=656, id="WX_656_LUDICOLO_RIME", base="LUDICOLO", baseName="Ludicolo", variant="RIME", types={ "WATER", "ICE" }, weather="Hail", cohort=4, rarity="rare", kantoReforged=true },
  { n=657, id="WX_657_SEEDOT_AUTUMN", base="SEEDOT", baseName="Seedot", variant="AUTUMN", types={ "GRASS", "GHOST" }, weather="Autumn Rain", cohort=4, rarity="rare", kantoReforged=true },
  { n=658, id="WX_658_NUZLEAF_AUTUMN", base="NUZLEAF", baseName="Nuzleaf", variant="AUTUMN", types={ "GRASS", "GHOST" }, weather="Autumn Rain", cohort=4, rarity="rare", kantoReforged=true },
  { n=659, id="WX_659_SHIFTRY_AUTUMN", base="SHIFTRY", baseName="Shiftry", variant="AUTUMN", types={ "GRASS", "GHOST" }, weather="Autumn Rain", cohort=4, rarity="rare", kantoReforged=true },
  { n=660, id="WX_660_TAILLOW_UMBRAL", base="TAILLOW", baseName="Taillow", variant="UMBRAL", types={ "NORMAL", "DARK" }, weather="Eclipse", cohort=4, rarity="rare", kantoReforged=true },
  { n=661, id="WX_661_SWELLOW_UMBRAL", base="SWELLOW", baseName="Swellow", variant="UMBRAL", types={ "NORMAL", "DARK" }, weather="Eclipse", cohort=4, rarity="rare", kantoReforged=true },
  { n=662, id="WX_662_WINGULL_RIME", base="WINGULL", baseName="Wingull", variant="RIME", types={ "WATER", "ICE" }, weather="Hail", cohort=4, rarity="rare", kantoReforged=true },
  { n=663, id="WX_663_PELIPPER_RIME", base="PELIPPER", baseName="Pelipper", variant="RIME", types={ "WATER", "ICE" }, weather="Hail", cohort=4, rarity="rare", kantoReforged=true },
  { n=664, id="WX_664_RALTS_ECLIPSE", base="RALTS", baseName="Ralts", variant="ECLIPSE", types={ "PSYCHIC_TYPE", "DARK" }, weather="Eclipse", cohort=4, rarity="rare", kantoReforged=true },
  { n=665, id="WX_665_KIRLIA_ECLIPSE", base="KIRLIA", baseName="Kirlia", variant="ECLIPSE", types={ "PSYCHIC_TYPE", "DARK" }, weather="Eclipse", cohort=4, rarity="rare", kantoReforged=true },
  { n=666, id="WX_666_GARDEVOIR_ECLIPSE", base="GARDEVOIR", baseName="Gardevoir", variant="ECLIPSE", types={ "PSYCHIC_TYPE", "DARK" }, weather="Eclipse", cohort=4, rarity="rare", kantoReforged=true },
  { n=667, id="WX_667_SURSKIT_ASHEN", base="SURSKIT", baseName="Surskit", variant="ASHEN", types={ "BUG", "FIRE" }, weather="Ashfall", cohort=4, rarity="rare", kantoReforged=true },
  { n=668, id="WX_668_MASQUERAIN_ASHEN", base="MASQUERAIN", baseName="Masquerain", variant="ASHEN", types={ "BUG", "FIRE" }, weather="Ashfall", cohort=4, rarity="rare", kantoReforged=true },
  { n=669, id="WX_669_SHROOMISH_AUTUMN", base="SHROOMISH", baseName="Shroomish", variant="AUTUMN", types={ "GRASS", "GHOST" }, weather="Autumn Rain", cohort=4, rarity="rare", kantoReforged=true },
  { n=670, id="WX_670_BRELOOM_AUTUMN", base="BRELOOM", baseName="Breloom", variant="AUTUMN", types={ "GRASS", "GHOST" }, weather="Autumn Rain", cohort=4, rarity="rare", kantoReforged=true },
  { n=671, id="WX_671_SLAKOTH_UMBRAL", base="SLAKOTH", baseName="Slakoth", variant="UMBRAL", types={ "NORMAL", "DARK" }, weather="Eclipse", cohort=4, rarity="rare", kantoReforged=true },
  { n=672, id="WX_672_VIGOROTH_UMBRAL", base="VIGOROTH", baseName="Vigoroth", variant="UMBRAL", types={ "NORMAL", "DARK" }, weather="Eclipse", cohort=4, rarity="rare", kantoReforged=true },
  { n=673, id="WX_673_SLAKING_UMBRAL", base="SLAKING", baseName="Slaking", variant="UMBRAL", types={ "NORMAL", "DARK" }, weather="Eclipse", cohort=4, rarity="rare", kantoReforged=true },
  { n=674, id="WX_674_NINCADA_ASHEN", base="NINCADA", baseName="Nincada", variant="ASHEN", types={ "BUG", "FIRE" }, weather="Ashfall", cohort=4, rarity="rare", kantoReforged=true },
  { n=675, id="WX_675_NINJASK_ASHEN", base="NINJASK", baseName="Ninjask", variant="ASHEN", types={ "BUG", "FIRE" }, weather="Ashfall", cohort=4, rarity="rare", kantoReforged=true },
  { n=676, id="WX_676_SHEDINJA_ASHEN", base="SHEDINJA", baseName="Shedinja", variant="ASHEN", types={ "BUG", "FIRE" }, weather="Ashfall", cohort=4, rarity="rare", kantoReforged=true },
  { n=677, id="WX_677_WHISMUR_UMBRAL", base="WHISMUR", baseName="Whismur", variant="UMBRAL", types={ "NORMAL", "DARK" }, weather="Eclipse", cohort=4, rarity="rare", kantoReforged=true },
  { n=678, id="WX_678_LOUDRED_UMBRAL", base="LOUDRED", baseName="Loudred", variant="UMBRAL", types={ "NORMAL", "DARK" }, weather="Eclipse", cohort=4, rarity="rare", kantoReforged=true },
  { n=679, id="WX_679_EXPLOUD_UMBRAL", base="EXPLOUD", baseName="Exploud", variant="UMBRAL", types={ "NORMAL", "DARK" }, weather="Eclipse", cohort=4, rarity="rare", kantoReforged=true },
  { n=680, id="WX_680_MAKUHITA_IRON", base="MAKUHITA", baseName="Makuhita", variant="IRON", types={ "FIGHTING", "STEEL" }, weather="Dust Storm", cohort=4, rarity="rare", kantoReforged=true },
  { n=681, id="WX_681_HARIYAMA_IRON", base="HARIYAMA", baseName="Hariyama", variant="IRON", types={ "FIGHTING", "STEEL" }, weather="Dust Storm", cohort=4, rarity="rare", kantoReforged=true },
  { n=682, id="WX_682_AZURILL_UMBRAL", base="AZURILL", baseName="Azurill", variant="UMBRAL", types={ "NORMAL", "DARK" }, weather="Eclipse", cohort=4, rarity="rare", kantoReforged=true },
  { n=683, id="WX_683_NOSEPASS_FOSSILFROST", base="NOSEPASS", baseName="Nosepass", variant="FOSSILFROST", types={ "ROCK", "ICE" }, weather="Hail", cohort=4, rarity="rare", kantoReforged=true },
  { n=684, id="WX_684_SKITTY_UMBRAL", base="SKITTY", baseName="Skitty", variant="UMBRAL", types={ "NORMAL", "DARK" }, weather="Eclipse", cohort=4, rarity="rare", kantoReforged=true },
  { n=685, id="WX_685_DELCATTY_UMBRAL", base="DELCATTY", baseName="Delcatty", variant="UMBRAL", types={ "NORMAL", "DARK" }, weather="Eclipse", cohort=4, rarity="rare", kantoReforged=true },
  { n=686, id="WX_686_SABLEYE_DUST", base="SABLEYE", baseName="Sableye", variant="DUST", types={ "DARK", "GROUND" }, weather="Dust Storm", cohort=4, rarity="rare", kantoReforged=true },
  { n=687, id="WX_687_MAWILE_STATIC", base="MAWILE", baseName="Mawile", variant="STATIC", types={ "STEEL", "ELECTRIC" }, weather="Thunderstorm", cohort=4, rarity="rare", kantoReforged=true },
  { n=688, id="WX_688_ARON_STATIC", base="ARON", baseName="Aron", variant="STATIC", types={ "STEEL", "ELECTRIC" }, weather="Thunderstorm", cohort=4, rarity="rare", kantoReforged=true },
  { n=689, id="WX_689_LAIRON_STATIC", base="LAIRON", baseName="Lairon", variant="STATIC", types={ "STEEL", "ELECTRIC" }, weather="Thunderstorm", cohort=4, rarity="rare", kantoReforged=true },
  { n=690, id="WX_690_AGGRON_STATIC", base="AGGRON", baseName="Aggron", variant="STATIC", types={ "STEEL", "ELECTRIC" }, weather="Thunderstorm", cohort=4, rarity="rare", kantoReforged=true },
  { n=691, id="WX_691_MEDITITE_IRON", base="MEDITITE", baseName="Meditite", variant="IRON", types={ "FIGHTING", "STEEL" }, weather="Dust Storm", cohort=4, rarity="rare", kantoReforged=true },
  { n=692, id="WX_692_MEDICHAM_IRON", base="MEDICHAM", baseName="Medicham", variant="IRON", types={ "FIGHTING", "STEEL" }, weather="Dust Storm", cohort=4, rarity="rare", kantoReforged=true },
  { n=693, id="WX_693_ELECTRIKE_AURORA", base="ELECTRIKE", baseName="Electrike", variant="AURORA", types={ "ELECTRIC", "FAIRY" }, weather="Aurora", cohort=4, rarity="rare", kantoReforged=true },
  { n=694, id="WX_694_MANECTRIC_AURORA", base="MANECTRIC", baseName="Manectric", variant="AURORA", types={ "ELECTRIC", "FAIRY" }, weather="Aurora", cohort=4, rarity="rare", kantoReforged=true },
  { n=695, id="WX_695_PLUSLE_AURORA", base="PLUSLE", baseName="Plusle", variant="AURORA", types={ "ELECTRIC", "FAIRY" }, weather="Aurora", cohort=4, rarity="rare", kantoReforged=true },
  { n=696, id="WX_696_MINUN_AURORA", base="MINUN", baseName="Minun", variant="AURORA", types={ "ELECTRIC", "FAIRY" }, weather="Aurora", cohort=4, rarity="rare", kantoReforged=true },
  { n=697, id="WX_697_VOLBEAT_ASHEN", base="VOLBEAT", baseName="Volbeat", variant="ASHEN", types={ "BUG", "FIRE" }, weather="Ashfall", cohort=4, rarity="rare", kantoReforged=true },
  { n=698, id="WX_698_ILLUMISE_ASHEN", base="ILLUMISE", baseName="Illumise", variant="ASHEN", types={ "BUG", "FIRE" }, weather="Ashfall", cohort=4, rarity="rare", kantoReforged=true },
  { n=699, id="WX_699_ROSELIA_AUTUMN", base="ROSELIA", baseName="Roselia", variant="AUTUMN", types={ "GRASS", "GHOST" }, weather="Autumn Rain", cohort=4, rarity="rare", kantoReforged=true },
  { n=700, id="WX_700_GULPIN_SMOG", base="GULPIN", baseName="Gulpin", variant="SMOG", types={ "POISON", "DARK" }, weather="Smog", cohort=4, rarity="rare", kantoReforged=true },
  { n=701, id="WX_701_SWALOT_SMOG", base="SWALOT", baseName="Swalot", variant="SMOG", types={ "POISON", "DARK" }, weather="Smog", cohort=4, rarity="rare", kantoReforged=true },
  { n=702, id="WX_702_CARVANHA_RIME", base="CARVANHA", baseName="Carvanha", variant="RIME", types={ "WATER", "ICE" }, weather="Hail", cohort=4, rarity="rare", kantoReforged=true },
  { n=703, id="WX_703_SHARPEDO_RIME", base="SHARPEDO", baseName="Sharpedo", variant="RIME", types={ "WATER", "ICE" }, weather="Hail", cohort=4, rarity="rare", kantoReforged=true },
  { n=704, id="WX_704_WAILMER_RIME", base="WAILMER", baseName="Wailmer", variant="RIME", types={ "WATER", "ICE" }, weather="Hail", cohort=4, rarity="rare", kantoReforged=true },
  { n=705, id="WX_705_WAILORD_RIME", base="WAILORD", baseName="Wailord", variant="RIME", types={ "WATER", "ICE" }, weather="Hail", cohort=4, rarity="rare", kantoReforged=true },
  { n=706, id="WX_706_NUMEL_SOLAR", base="NUMEL", baseName="Numel", variant="SOLAR", types={ "FIRE", "DRAGON" }, weather="Heatwave", cohort=4, rarity="rare", kantoReforged=true },
  { n=707, id="WX_707_CAMERUPT_SOLAR", base="CAMERUPT", baseName="Camerupt", variant="SOLAR", types={ "FIRE", "DRAGON" }, weather="Heatwave", cohort=4, rarity="rare", kantoReforged=true },
  { n=708, id="WX_708_TORKOAL_SOLAR", base="TORKOAL", baseName="Torkoal", variant="SOLAR", types={ "FIRE", "DRAGON" }, weather="Heatwave", cohort=4, rarity="rare", kantoReforged=true },
  { n=709, id="WX_709_SPOINK_ECLIPSE", base="SPOINK", baseName="Spoink", variant="ECLIPSE", types={ "PSYCHIC_TYPE", "DARK" }, weather="Eclipse", cohort=4, rarity="rare", kantoReforged=true },
  { n=710, id="WX_710_GRUMPIG_ECLIPSE", base="GRUMPIG", baseName="Grumpig", variant="ECLIPSE", types={ "PSYCHIC_TYPE", "DARK" }, weather="Eclipse", cohort=4, rarity="rare", kantoReforged=true },
  { n=711, id="WX_711_SPINDA_UMBRAL", base="SPINDA", baseName="Spinda", variant="UMBRAL", types={ "NORMAL", "DARK" }, weather="Eclipse", cohort=4, rarity="rare", kantoReforged=true },
  { n=712, id="WX_712_TRAPINCH_MIRE", base="TRAPINCH", baseName="Trapinch", variant="MIRE", types={ "GROUND", "WATER" }, weather="Heavy Rain", cohort=4, rarity="rare", kantoReforged=true },
  { n=713, id="WX_713_VIBRAVA_MIRE", base="VIBRAVA", baseName="Vibrava", variant="MIRE", types={ "GROUND", "WATER" }, weather="Heavy Rain", cohort=4, rarity="rare", kantoReforged=true },
  { n=714, id="WX_714_FLYGON_MIRE", base="FLYGON", baseName="Flygon", variant="MIRE", types={ "GROUND", "WATER" }, weather="Heavy Rain", cohort=4, rarity="rare", kantoReforged=true },
  { n=715, id="WX_715_CACNEA_AUTUMN", base="CACNEA", baseName="Cacnea", variant="AUTUMN", types={ "GRASS", "GHOST" }, weather="Autumn Rain", cohort=4, rarity="rare", kantoReforged=true },
  { n=716, id="WX_716_CACTURNE_AUTUMN", base="CACTURNE", baseName="Cacturne", variant="AUTUMN", types={ "GRASS", "GHOST" }, weather="Autumn Rain", cohort=4, rarity="rare", kantoReforged=true },
  { n=717, id="WX_717_SWABLU_UMBRAL", base="SWABLU", baseName="Swablu", variant="UMBRAL", types={ "NORMAL", "DARK" }, weather="Eclipse", cohort=4, rarity="rare", kantoReforged=true },
  { n=718, id="WX_718_ALTARIA_ECLIPSE", base="ALTARIA", baseName="Altaria", variant="ECLIPSE", types={ "DRAGON", "DARK" }, weather="Eclipse", cohort=4, rarity="rare", kantoReforged=true },
  { n=719, id="WX_719_ZANGOOSE_UMBRAL", base="ZANGOOSE", baseName="Zangoose", variant="UMBRAL", types={ "NORMAL", "DARK" }, weather="Eclipse", cohort=4, rarity="rare", kantoReforged=true },
  { n=720, id="WX_720_SEVIPER_SMOG", base="SEVIPER", baseName="Seviper", variant="SMOG", types={ "POISON", "DARK" }, weather="Smog", cohort=4, rarity="rare", kantoReforged=true },
  { n=721, id="WX_721_LUNATONE_FOSSILFROST", base="LUNATONE", baseName="Lunatone", variant="FOSSILFROST", types={ "ROCK", "ICE" }, weather="Hail", cohort=4, rarity="rare", kantoReforged=true },
  { n=722, id="WX_722_SOLROCK_FOSSILFROST", base="SOLROCK", baseName="Solrock", variant="FOSSILFROST", types={ "ROCK", "ICE" }, weather="Hail", cohort=4, rarity="rare", kantoReforged=true },
  { n=723, id="WX_723_BARBOACH_RIME", base="BARBOACH", baseName="Barboach", variant="RIME", types={ "WATER", "ICE" }, weather="Hail", cohort=4, rarity="rare", kantoReforged=true },
  { n=724, id="WX_724_WHISCASH_RIME", base="WHISCASH", baseName="Whiscash", variant="RIME", types={ "WATER", "ICE" }, weather="Hail", cohort=4, rarity="rare", kantoReforged=true },
  { n=725, id="WX_725_CORPHISH_RIME", base="CORPHISH", baseName="Corphish", variant="RIME", types={ "WATER", "ICE" }, weather="Hail", cohort=4, rarity="rare", kantoReforged=true },
  { n=726, id="WX_726_CRAWDAUNT_RIME", base="CRAWDAUNT", baseName="Crawdaunt", variant="RIME", types={ "WATER", "ICE" }, weather="Hail", cohort=4, rarity="rare", kantoReforged=true },
  { n=727, id="WX_727_BALTOY_MIRE", base="BALTOY", baseName="Baltoy", variant="MIRE", types={ "GROUND", "WATER" }, weather="Heavy Rain", cohort=4, rarity="rare", kantoReforged=true },
  { n=728, id="WX_728_CLAYDOL_MIRE", base="CLAYDOL", baseName="Claydol", variant="MIRE", types={ "GROUND", "WATER" }, weather="Heavy Rain", cohort=4, rarity="rare", kantoReforged=true },
  { n=729, id="WX_729_LILEEP_FOSSILFROST", base="LILEEP", baseName="Lileep", variant="FOSSILFROST", types={ "ROCK", "ICE" }, weather="Hail", cohort=4, rarity="rare", kantoReforged=true },
  { n=730, id="WX_730_CRADILY_FOSSILFROST", base="CRADILY", baseName="Cradily", variant="FOSSILFROST", types={ "ROCK", "ICE" }, weather="Hail", cohort=4, rarity="rare", kantoReforged=true },
  { n=731, id="WX_731_ANORITH_FOSSILFROST", base="ANORITH", baseName="Anorith", variant="FOSSILFROST", types={ "ROCK", "ICE" }, weather="Hail", cohort=4, rarity="rare", kantoReforged=true },
  { n=732, id="WX_732_ARMALDO_FOSSILFROST", base="ARMALDO", baseName="Armaldo", variant="FOSSILFROST", types={ "ROCK", "ICE" }, weather="Hail", cohort=4, rarity="rare", kantoReforged=true },
  { n=733, id="WX_733_FEEBAS_RIME", base="FEEBAS", baseName="Feebas", variant="RIME", types={ "WATER", "ICE" }, weather="Hail", cohort=4, rarity="rare", kantoReforged=true },
  { n=734, id="WX_734_MILOTIC_RIME", base="MILOTIC", baseName="Milotic", variant="RIME", types={ "WATER", "ICE" }, weather="Hail", cohort=4, rarity="rare", kantoReforged=true },
  { n=735, id="WX_735_CASTFORM_UMBRAL", base="CASTFORM", baseName="Castform", variant="UMBRAL", types={ "NORMAL", "DARK" }, weather="Eclipse", cohort=4, rarity="rare", kantoReforged=true },
  { n=736, id="WX_736_KECLEON_UMBRAL", base="KECLEON", baseName="Kecleon", variant="UMBRAL", types={ "NORMAL", "DARK" }, weather="Eclipse", cohort=4, rarity="rare", kantoReforged=true },
  { n=737, id="WX_737_SHUPPET_STATIC", base="SHUPPET", baseName="Shuppet", variant="STATIC", types={ "GHOST", "ELECTRIC" }, weather="Static Storm", cohort=4, rarity="rare", kantoReforged=true },
  { n=738, id="WX_738_BANETTE_STATIC", base="BANETTE", baseName="Banette", variant="STATIC", types={ "GHOST", "ELECTRIC" }, weather="Static Storm", cohort=4, rarity="rare", kantoReforged=true },
  { n=739, id="WX_739_DUSKULL_STATIC", base="DUSKULL", baseName="Duskull", variant="STATIC", types={ "GHOST", "ELECTRIC" }, weather="Static Storm", cohort=4, rarity="rare", kantoReforged=true },
  { n=740, id="WX_740_DUSCLOPS_STATIC", base="DUSCLOPS", baseName="Dusclops", variant="STATIC", types={ "GHOST", "ELECTRIC" }, weather="Static Storm", cohort=4, rarity="rare", kantoReforged=true },
  { n=741, id="WX_741_TROPIUS_AUTUMN", base="TROPIUS", baseName="Tropius", variant="AUTUMN", types={ "GRASS", "GHOST" }, weather="Autumn Rain", cohort=4, rarity="rare", kantoReforged=true },
  { n=742, id="WX_742_CHIMECHO_ECLIPSE", base="CHIMECHO", baseName="Chimecho", variant="ECLIPSE", types={ "PSYCHIC_TYPE", "DARK" }, weather="Eclipse", cohort=4, rarity="rare", kantoReforged=true },
  { n=743, id="WX_743_ABSOL_DUST", base="ABSOL", baseName="Absol", variant="DUST", types={ "DARK", "GROUND" }, weather="Dust Storm", cohort=4, rarity="rare", kantoReforged=true },
  { n=744, id="WX_744_WYNAUT_ECLIPSE", base="WYNAUT", baseName="Wynaut", variant="ECLIPSE", types={ "PSYCHIC_TYPE", "DARK" }, weather="Eclipse", cohort=4, rarity="rare", kantoReforged=true },
  { n=745, id="WX_745_SNORUNT_AURORA", base="SNORUNT", baseName="Snorunt", variant="AURORA", types={ "ICE", "PSYCHIC_TYPE" }, weather="Aurora", cohort=4, rarity="rare", kantoReforged=true },
  { n=746, id="WX_746_GLALIE_AURORA", base="GLALIE", baseName="Glalie", variant="AURORA", types={ "ICE", "PSYCHIC_TYPE" }, weather="Aurora", cohort=4, rarity="rare", kantoReforged=true },
  { n=747, id="WX_747_SPHEAL_AURORA", base="SPHEAL", baseName="Spheal", variant="AURORA", types={ "ICE", "PSYCHIC_TYPE" }, weather="Aurora", cohort=4, rarity="rare", kantoReforged=true },
  { n=748, id="WX_748_SEALEO_AURORA", base="SEALEO", baseName="Sealeo", variant="AURORA", types={ "ICE", "PSYCHIC_TYPE" }, weather="Aurora", cohort=4, rarity="rare", kantoReforged=true },
  { n=749, id="WX_749_WALREIN_AURORA", base="WALREIN", baseName="Walrein", variant="AURORA", types={ "ICE", "PSYCHIC_TYPE" }, weather="Aurora", cohort=4, rarity="rare", kantoReforged=true },
  { n=750, id="WX_750_CLAMPERL_RIME", base="CLAMPERL", baseName="Clamperl", variant="RIME", types={ "WATER", "ICE" }, weather="Hail", cohort=4, rarity="rare", kantoReforged=true },
  { n=751, id="WX_751_HUNTAIL_RIME", base="HUNTAIL", baseName="Huntail", variant="RIME", types={ "WATER", "ICE" }, weather="Hail", cohort=4, rarity="rare", kantoReforged=true },
  { n=752, id="WX_752_GOREBYSS_RIME", base="GOREBYSS", baseName="Gorebyss", variant="RIME", types={ "WATER", "ICE" }, weather="Hail", cohort=4, rarity="rare", kantoReforged=true },
  { n=753, id="WX_753_RELICANTH_RIME", base="RELICANTH", baseName="Relicanth", variant="RIME", types={ "WATER", "ICE" }, weather="Hail", cohort=4, rarity="veryRare", kantoReforged=true },
  { n=754, id="WX_754_LUVDISC_RIME", base="LUVDISC", baseName="Luvdisc", variant="RIME", types={ "WATER", "ICE" }, weather="Hail", cohort=4, rarity="rare", kantoReforged=true },
  { n=755, id="WX_755_BAGON_ECLIPSE", base="BAGON", baseName="Bagon", variant="ECLIPSE", types={ "DRAGON", "DARK" }, weather="Eclipse", cohort=4, rarity="rare", kantoReforged=true },
  { n=756, id="WX_756_SHELGON_ECLIPSE", base="SHELGON", baseName="Shelgon", variant="ECLIPSE", types={ "DRAGON", "DARK" }, weather="Eclipse", cohort=4, rarity="rare", kantoReforged=true },
  { n=757, id="WX_757_SALAMENCE_ECLIPSE", base="SALAMENCE", baseName="Salamence", variant="ECLIPSE", types={ "DRAGON", "DARK" }, weather="Eclipse", cohort=4, rarity="rare", kantoReforged=true },
  { n=758, id="WX_758_BELDUM_STATIC", base="BELDUM", baseName="Beldum", variant="STATIC", types={ "STEEL", "ELECTRIC" }, weather="Thunderstorm", cohort=4, rarity="legendary", kantoReforged=true },
  { n=759, id="WX_759_METANG_STATIC", base="METANG", baseName="Metang", variant="STATIC", types={ "STEEL", "ELECTRIC" }, weather="Thunderstorm", cohort=4, rarity="legendary", kantoReforged=true },
  { n=760, id="WX_760_METAGROSS_STATIC", base="METAGROSS", baseName="Metagross", variant="STATIC", types={ "STEEL", "ELECTRIC" }, weather="Thunderstorm", cohort=4, rarity="legendary", kantoReforged=true },
  { n=761, id="WX_761_REGIROCK_FOSSILFROST", base="REGIROCK", baseName="Regirock", variant="FOSSILFROST", types={ "ROCK", "ICE" }, weather="Hail", cohort=4, rarity="legendary", kantoReforged=true },
  { n=762, id="WX_762_REGICE_AURORA", base="REGICE", baseName="Regice", variant="AURORA", types={ "ICE", "PSYCHIC_TYPE" }, weather="Aurora", cohort=4, rarity="legendary", kantoReforged=true },
  { n=763, id="WX_763_REGISTEEL_STATIC", base="REGISTEEL", baseName="Registeel", variant="STATIC", types={ "STEEL", "ELECTRIC" }, weather="Thunderstorm", cohort=4, rarity="legendary", kantoReforged=true },
  { n=764, id="WX_764_LATIAS_ECLIPSE", base="LATIAS", baseName="Latias", variant="ECLIPSE", types={ "DRAGON", "DARK" }, weather="Eclipse", cohort=4, rarity="legendary", kantoReforged=true },
  { n=765, id="WX_765_LATIOS_ECLIPSE", base="LATIOS", baseName="Latios", variant="ECLIPSE", types={ "DRAGON", "DARK" }, weather="Eclipse", cohort=4, rarity="legendary", kantoReforged=true },
  { n=766, id="WX_766_KYOGRE_RIME", base="KYOGRE", baseName="Kyogre", variant="RIME", types={ "WATER", "ICE" }, weather="Hail", cohort=4, rarity="legendary", kantoReforged=true },
  { n=767, id="WX_767_GROUDON_MIRE", base="GROUDON", baseName="Groudon", variant="MIRE", types={ "GROUND", "WATER" }, weather="Heavy Rain", cohort=4, rarity="legendary", kantoReforged=true },
  { n=768, id="WX_768_RAYQUAZA_ECLIPSE", base="RAYQUAZA", baseName="Rayquaza", variant="ECLIPSE", types={ "DRAGON", "DARK" }, weather="Eclipse", cohort=4, rarity="legendary", kantoReforged=true },
  { n=769, id="WX_769_JIRACHI_STATIC", base="JIRACHI", baseName="Jirachi", variant="STATIC", types={ "STEEL", "ELECTRIC" }, weather="Thunderstorm", cohort=4, rarity="legendary", kantoReforged=true },
  { n=770, id="WX_770_DEOXYS_NORMAL_ECLIPSE", base="DEOXYS_NORMAL", baseName="Deoxys Normal", variant="ECLIPSE", types={ "PSYCHIC_TYPE", "DARK" }, weather="Eclipse", cohort=4, rarity="legendary", kantoReforged=true },
}
return variants
